### ISSUE TITLE
Use fig ?

### ISSUE THREAD

**Issue by ronanM** [metabrainz/musicbrainz-docker#1]
Why not use fig for launching/config all the containers.

http://www.fig.sh

Regards.

**Comment by jsturgis** [comment]
Good idea feel free to make a pull request, I will try to get it done though.

**Comment by ronanM** [comment]
I've forked @captnbp repo https://github.com/captnbp/musicbrainz-docker for two little modifications

 https://github.com/ronanM/musicbrainz-docker

**Comment by jsturgis** [comment]
Cool thanks I am going to use docker-compose instead.
