### ISSUE TITLE
Database creation fails

### ISSUE THREAD

**Issue by volgin** [metabrainz/musicbrainz-docker#100]
I tried the latest update today, and it runs into the following error:

Sun May 19 20:31:38 2019 : InitDb.pl starting
ERROR:  schema "musicbrainz" already exists
ERROR:  schema "cover_art_archive" already exists
ERROR:  schema "documentation" already exists
ERROR:  schema "json_dump" already exists
ERROR:  schema "report" already exists
ERROR:  schema "sitemaps" already exists
ERROR:  schema "statistics" already exists
ERROR:  schema "wikidocs" already exists
Sun May 19 20:31:38 2019 : Installing extensions (Extensions.sql)
Sun May 19 20:31:38 2019 : Creating tables ... (CreateTables.sql)
Sun May 19 20:31:39 2019 : psql:/musicbrainz-server/admin/sql/CreateTables.sql:15: ERROR:  relation "alternative_release" already exists
Error during CreateTables.sql at /musicbrainz-server/admin/InitDb.pl line 117.
Sun May 19 20:31:39 2019 : InitDb.pl failed
Sun May 19 20:31:39 2019 : InitDb.pl starting
Sun May 19 20:31:39 2019 : Creating database 'musicbrainz_db'
Failed query:
	'CREATE DATABASE musicbrainz_db WITH OWNER = musicbrainz TEMPLATE template0 ENCODING = 'UNICODE' LC_CTYPE='C' LC_COLLATE='C''
	()
42P04 DBD::Pg::st execute failed: ERROR:  database "musicbrainz_db" already exists [for Statement "CREATE DATABASE musicbrainz_db WITH OWNER = musicbrainz TEMPLATE template0 ENCODING = 'UNICODE' LC_CTYPE='C' LC_COLLATE='C'"]
 at /musicbrainz-server/admin/../lib/Sql.pm line 115.
	Sql::catch {...} (MusicBrainz::Server::Exceptions::DatabaseError=HASH(0x3fd7d88)) called at /usr/share/perl5/Try/Tiny.pm line 115
	Try::Tiny::try(CODE(0x3eea798), Try::Tiny::Catch=REF(0x369f7c0)) called at /musicbrainz-server/admin/../lib/Sql.pm line 116
	Sql::do(Sql=HASH(0x3d9dac0), "CREATE DATABASE musicbrainz_db WITH OWNER = musicbrainz TEMPL"...) called at /musicbrainz-server/admin/InitDb.pl line 218
	main::Create("MAINTENANCE") called at /musicbrainz-server/admin/InitDb.pl line 526
Sun May 19 20:31:39 2019 : InitDb.pl failed

**Comment by yvanzo** [comment]
According to your previous issue, I assume you don’t need to keep the already existing database, then the easiest here would be to [recreate the database](https://github.com/metabrainz/musicbrainz-docker#if-you-need-to-recreate-the-database).

**Comment by volgin** [comment]
I tried that first. Then I wiped out everything and started from scratch. That's when I saw this error.

Are there some steps to erase the previous installation other than deleting the entire folder?

**Comment by volgin** [comment]
But when I try recreatedb.sh, I again get this error message:

Mon May 20 16:21:17 2019 : Schema sequence mismatch - codebase is 24, mbdump.tar.bz2 is 25

**Comment by yvanzo** [comment]
Deleting the entire folder doesn’t remove docker volumes, images and containers which are stored system-wide (in `/var/lib/docker/` for Ubuntu 18.04 Bionic). These can be erased either by hand or by running `docker-compose down --rmi all --volumes` from the `musicbrainz-docker` folder.

But you probably don’t have to, instead make sure codebase is 25 by rebuilding the docker image for the musicbrainz service as follows:
```bash
docker-compose rm --stop musicbrainz
docker-compose build musicbrainz
```
Only then recreate the database.

**Comment by volgin** [comment]
After I ran these, I have the following containers:

```
musicbrainz-docker_search_1
musicbrainz-docker_db_1
musicbrainz-docker_redis_1
```

Therefore, any connabd from the documentation results in:
`No such container: musicbrainz-docker_musicbrainz_1`

How do I get this container up and running?

**Comment by yvanzo** [comment]
Using `docker-compose up -d` again as in https://github.com/metabrainz/musicbrainz-docker#installation

**Comment by volgin** [comment]
Thank you for your help!
