### ISSUE TITLE
Manual schema upgrade fails / Can't locate JSON.pm in

### ISSUE THREAD

**Issue by PeterCodar** [metabrainz/musicbrainz-docker#101]
I try to upgrade my VM/docker with the instructions on
https://github.com/metabrainz/musicbrainz-docker#handling-schema-updates
but the upgrade script `./upgrade.sh` fails with:

![musicbrainz-server-2018-08-14-2019-05-20-10-30-35](https://user-images.githubusercontent.com/18629146/58007472-9e670b80-7aea-11e9-9457-83bd6d639be7.png)

What do I have to do?

**Comment by yvanzo** [comment]
You have to enable Perl local lib with
```bash
eval $( perl -Mlocal::lib )
```
before running `./upgrade.sh`.

**Comment by PeterCodar** [comment]
@yvanzo Thank you! With your additional eval-command the upgrade works fine.
Maybe you should add it to the official README.md?

**Comment by yvanzo** [comment]
Thanks for the update, fixed schema update instructions with commit https://github.com/metabrainz/musicbrainz-docker/commit/923b641b6de1d005bc2320ee20302007bf527371.
