### ISSUE TITLE
Accessing database from the terminal

### ISSUE THREAD

**Issue by volgin** [metabrainz/musicbrainz-docker#102]
I run a docker, and I can successfully access musicbrainz web service through localhost:5000.

I can also connect to the database through the terminal by using:

`psql -h localhost -U musicbrainz -p 5432`

However, `/dt` shows "Did not find any relations". Am I missing some step in accessing the database which runs in docker?

**Comment by yvanzo** [comment]
When you don’t give the database name, `psql` assumes it is the same as the user name `musicbrainz`, while `musicbrainz-docker` currently uses `musicbrainz_db` instead, see https://github.com/metabrainz/musicbrainz-docker/blob/17550be919e5acf295e341966c4da3c13122b5cd/musicbrainz-dockerfile/DBDefs.pm#L80

Try to connect with:
```
psql -h localhost -U musicbrainz -d musicbrainz_db -p 5432
```

**Comment by volgin** [comment]
Makes sense, thank you!
