### ISSUE TITLE
README.md : musicbrainz docker image name

### ISSUE THREAD

**Issue by niko2** [metabrainz/musicbrainz-docker#104]
in README.md mucisbrainz default docker image name is musicbrainzdocker_musicbrainz_1, but when executing all commands, the name is musicbrainz-docker_musicbrainz_1

**Comment by niko2** [comment]
made a PR

**Comment by niko2** [comment]
https://github.com/metabrainz/musicbrainz-docker/pull/103

**Comment by yvanzo** [comment]
This is due to docker-compose 1.21.0-rc1 having changed the name generated by default.
Duplicates issue https://github.com/metabrainz/musicbrainz-docker/issues/97.
Resolved by commit https://github.com/metabrainz/musicbrainz-docker/commit/2261442974ad44358495996bc76c872a922db1c9.
