### ISSUE TITLE
slave.log is rotated as soon as replication is done

### ISSUE THREAD

**Issue by niko2** [metabrainz/musicbrainz-docker#105]
Hello,
Readme is showing how to watch the replication status, but it is only available while it is running since slave.log is rotated as soon as replication is done. And it is running nightly, so it is unlikely we will watch it while running !
Should the documentation mentionned that ?
Or (even better) should the log rotation occur before the replication, so that we have the full day to read it ?

**Comment by yvanzo** [comment]
Hi @niko2,

Good catch, thank you, the documentation is indeed misleading as `slave.log.1` should be read instead when the replication is done. It is now mentioned in the documentation, and you still have the full day (actually the full month) to read replication log.

Note: Changing the log rotation requires to change the script actually doing replication in [MBS repository](https://github.com/metabrainz/musicbrainz-server) at [admin/cron/slave.sh](https://github.com/metabrainz/musicbrainz-server/blob/v-2019-06-03/admin/cron/slave.sh). Please fill a [ticket](https://tickets.metabrainz.org/secure/CreateIssueDetails!init.jspa?pid=10000&issuetype=4&components=10046) and/or open a [pull request](https://musicbrainz.org/doc/Development/Git) for any improvement you want to.
