### ISSUE TITLE
Specific lookup errors with new SOLR search server

### ISSUE THREAD

**Issue by PeterCodar** [metabrainz/musicbrainz-docker#108]
The new [SOLR search server](https://github.com/metabrainz/musicbrainz-docker/issues/86) works fine now (one known exception: annotations).

During my actual tagging session with Picard v2.1.3 and the local SOLR search server, I have found a few lookup queries who returns only such an error:

> Oops, something went wrong!
> 
> Error message: (No details about this error are available)
> 
> Time: 2019-08-15 16:56:17 UTC
> 
> Host: 72e66089454d
> 
> Interface language: en
> 
> URL: http://192.168.1.61:5000/taglookup?artist=Various%20Artists&release=Time-Life%20AM%20Gold%201963&track=&tracknum=&duration=&filename=&tport=8000
> 
> Request data:
> 
> $VAR1 = {
>           'body_parameters' => {},
>           'query_parameters' => {
>                                   'track' => '',
>                                   'duration' => '',
>                                   'artist' => 'Various Artists',
>                                   'filename' => '',
>                                   'tracknum' => '',
>                                   'release' => 'Time-Life AM Gold 1963',
>                                   'tport' => '8000'
>                                 }
>         };
>     
> We're terribly sorry for this problem. Please wait a few minutes and repeat your request — the problem may go away.

Other queries from the same Picard to the same SOLR works perfect. This are only a very few producing the above error. Maybe someone could have a look at the syntax or other possible reasons?
Hint: The same lookups against "musicbrainz.org" instead to "192.168.1.61:5000" runs without error.

Examples for above error:
http://192.168.1.61:5000/taglookup?artist=Various%20Artists&release=Time-Life%20AM%20Gold%201963&track=&tracknum=&duration=&filename=&tport=8000

#2 Example:
http://192.168.1.61:5000/search/textsearch?limit=25&type=release&query=time%20life%2080s%20music%20explosion&tport=8000

#3 Example:
http://192.168.1.61:5000/taglookup?artist=Various&release=Body%20%26%20Soul%20(disc%201)&track=&tracknum=&duration=&filename=&tport=8000

**Comment by yvanzo** [comment]
This is not an issue about docker.
I would suggest to post to https://community.metabrainz.org/ instead.
Thank you!
