### ISSUE TITLE
Donation Nag Screen for local server?

### ISSUE THREAD

**Issue by PeterCodar** [metabrainz/musicbrainz-docker#109]
Actually I get the following error on my local running MB Server executing a taglookup:

> The users make MusicBrainz happen and we appreciate your help!
> 
> However, we still have to pay the bills and hosting this site costs more than $1000 per month. We need our users to help us make ends meet and hopefully have money left over to sponsor more development. The MetaBrainz Foundation, a California based 501(c)3 tax-exempt non-profit, operates the MusicBrainz project which makes all donations tax deductible for US taxpayers. And it's simply good karma everywhere else!
> 
> If you donate $4 you will not get this nag text for a month. We encourage people to donate $12 to make the nag screen disappear for 3 months. Or even better, sign up for a recurring donation every three months to not have to think about or see this nag again.

**Is it really necessary to show such a nag screen on a local copy of MB Server?**

**Comment by yvanzo** [comment]
This is a bug of MusicBrainz Server. As local copy cannot replicate data about editors, it wrongly assumes that local users didn’t make a donation. Just reported as ticket [MBS-10320](https://tickets.metabrainz.org/browse/MBS-10320) for follow-up.

P.S. I don’t recall having ever seen this screen before.
