### ISSUE TITLE
Don't forget to fix this 'annotations'

### ISSUE THREAD

**Issue by PeterCodar** [metabrainz/musicbrainz-docker#115]
The import of this annotations still fails:

```
Skipping annotation with id 249425. The most likely cause of this is an unsupported control character in the data.
Skipping annotation with id 470499. The most likely cause of this is an unsupported control character in the data.
Skipping annotation with id 480676. The most likely cause of this is an unsupported control character in the data.
Skipping annotation with id 481654. The most likely cause of this is an unsupported control character in the data.
Skipping annotation with id 496414. The most likely cause of this is an unsupported control character in the data.
Skipping annotation with id 612649. The most likely cause of this is an unsupported control character in the data.
Skipping annotation with id 612652. The most likely cause of this is an unsupported control character in the data.
Skipping annotation with id 641507. The most likely cause of this is an unsupported control character in the data.
Skipping annotation with id 669022. The most likely cause of this is an unsupported control character in the data.
Skipping annotation with id 669023. The most likely cause of this is an unsupported control character in the data.
Skipping annotation with id 672623. The most likely cause of this is an unsupported control character in the data.
Skipping annotation with id 669020. The most likely cause of this is an unsupported control character in the data.
Skipping annotation with id 671627. The most likely cause of this is an unsupported control character in the data.
Skipping annotation with id 678595. The most likely cause of this is an unsupported control character in the data.
Skipping annotation with id 669019. The most likely cause of this is an unsupported control character in the data.
Skipping annotation with id 683717. The most likely cause of this is an unsupported control character in the data.
Skipping annotation with id 687652. The most likely cause of this is an unsupported control character in the data.
Skipping annotation with id 774147. The most likely cause of this is an unsupported control character in the data.
```
The first annotation contains:

> Live concert recorded at BBC-Radio 1 on November 21, 2002. Plus rare B-sides and acoustic tracks.
Bar code: 1 011001 1000 1.
Track 8 mislabeled as ''Things'' on this release.
Track 11 also known as ''I Don't Give''.
Track 12 also known as ''Get Over It''.
Track 14 mislabeled as ''Nobody's Full'' on this release.
Track 18 is a cover version of [http://musicbrainz.org/artist/c2c70ed6-5f10-445c-969f-2c16bc9a4c2e.html|Sixpence None The Richer].
Tracks 10 to 13 are studio versions.
Index Track on the printing for Kiss Me (track 18) mispells ''Sixpence None The Richer'' as "''Six Pence None The Richer''".

The second annotation contains:

> Track 13 contains a hidden track. Full track breakdown:
00:00 - 04:10 : [http://musicbrainz.org/recording/b2e7d0c9-f13e-4ffd-8aa9-2ab7edf0d020|Til Kingdom Come] (4:10)
04:11 - 04:39 : &amp;#91;silence&amp;#93; (0:29)
04:40 - 08:43 : How You See the World (4:04)

Which ones are "unsupported control character in the data"?
If someone could tell us this characters, we could adjust them manually in the MB annotation.

**Comment by yvanzo** [comment]
It requires to make joined queries in the database to find the related entities I adjusted these, see [annotation edits](https://musicbrainz.org/search/edits?auto_edit_filter=&order=desc&negation=0&combinator=and&conditions.0.field=editor&conditions.0.operator=%3D&conditions.0.name=yvanzo&conditions.0.args.0=568745&conditions.1.field=open_time&conditions.1.operator=%3D&conditions.1.args.0=2019-10-09&conditions.1.args.1=&field=Please+choose+a+condition). It should be fixed with the next replication packet. I also created the ticket [MBS-10416](https://tickets.metabrainz.org/browse/MBS-10416) to prevent further annotations with such control characters.

**Comment by PeterCodar** [comment]
Looks good actually! All annotations imported, no more errors.
Thank you very much @yvanzo !

```
vagrant@ubuntu:~/musicbrainz-docker$ sudo sir-dockerfile/check-search-indexes.sh all

CORE           STATUS  INDEX     DB
editor         OK      0         /0
instrument     OK      961       /961
series         OK      10367     /10367
place          OK      37818     /37818
event          OK      38821     /38821
tag            OK      92496     /92496
area           OK      117906    /117906
label          OK      167672    /167672
cdstub         OK      292983    /292983
annotation     OK      330795    /330795
work           OK      1213387   /1213387
artist         OK      1552734   /1552734
release-group  OK      1849915   /1849915
release        OK      2336688   /2336688
url            OK      6038051   /6038051
recording      OK      21131158  /21131158

```
