### ISSUE TITLE
mbvm-38-dev documentation missing critical step

### ISSUE THREAD

**Issue by nelgin** [metabrainz/musicbrainz-docker#116]
https://github.com/metabrainz/musicbrainz-docker/blob/mbvm-38-dev/README.md

After the git clone and cd to musicbrainz-docker directory and before sudo docker-compose build
You need to specity 

git checkout mbvm-38-dev

If you don't complete this step then you'll end up with an error about indexer_1 not found when you try to create the indexes.

**Comment by yvanzo** [comment]
I’m not sure to understand:

> before ... sudo docker-compose build
> you need to specify ... sudo docker-compose build

**Comment by nelgin** [comment]
Sorry, it didn't copy into my buffer before pasting so it got the wrong line. I've fixed it now.

**Comment by yvanzo** [comment]
Fixed, thank you!
