### ISSUE TITLE
postgres extension error

### ISSUE THREAD

**Issue by wmorris92** [metabrainz/musicbrainz-docker#117]
Hello, I'm trying to run the `createdb.sh` script on a container but it errors at creating the extentions:

`Installing extensions (Extensions.sql)`
`psql:/musicbrainz-server/admin/sql/Extensions.sql:6: ERROR:  could not open extension control file "/opt/bitnami/postgresql/share/extension/musicbrainz_unaccent.control": No such file or directory`

Any hints to how to resolve, getting around the issue for now by commenting out the 2 musicbrainz extensions in the Extensions.sql file

**Comment by yvanzo** [comment]
Hi,

This repository is not based on Bitnami images, so I wonder why this log refers to `/opt/bitnami`. It might be that base images are loaded from Bitnami Images rather than Docker Official Images. Can you please tell more about your environment, is it Bitnami specific or something?

Full log of building `db` service might help too:

``` bash
sudo docker-compose build --no-cache --pull db
```

**Comment by wmorris92** [comment]
Hey, sorry, should have been more explicit - I'm attempting to put 3 of the containers into a kubernetes cluster and use our AWS RDS database instead. I have since updated the config in DBDefs to point to our RDS database, and that fixed that error above but instead now get
`psql:/musicbrainz-server/admin/sql/Extensions.sql:8: ERROR:  Extension "musicbrainz_unaccent" is not supported by Amazon RDS`
`DETAIL:  Installing the extension "musicbrainz_unaccent" failed, because it is not on the list of extensions supported by Amazon RDS.`
`HINT:  Amazon RDS allows users with rds_superuser role to install supported extensions. See: SHOW rds.extensions;`

Is it viable running the musicbrainz server without the extensions added?

**Comment by yvanzo** [comment]
Summarizing the answer here for the record: It is viable if you query the PostgreSQL database directly, it is not viable if you want to use local MusicBrainz webservice or website.
