### ISSUE TITLE
Expose musicbrainz-docker/default/indexer.ini as local file

### ISSUE THREAD

**Issue by JoshDi** [metabrainz/musicbrainz-docker#119]
Can we please include a variable, like you did with the replication.cron, so we can specify a local indexer.ini file? Thank you!

**Comment by yvanzo** [comment]
Indeed, that would be consistent with other `default/` files that can be overridden/replaced through Docker environment variables. It would also help debugging #110.

**Comment by yvanzo** [comment]
Resolved with the above commit to  [`mbvm-38-dev`](https://github.com/metabrainz/musicbrainz-docker/tree/mbvm-38-dev) branch.

**Comment by JoshDi** [comment]
Edit: see issue #120 for follow-up
