### ISSUE TITLE
Indexer Docker image will not stay running if SIR_CONFIG_PATH=./local/indexer.ini is set in .env with default parameters matching

### ISSUE THREAD

**Issue by JoshDi** [metabrainz/musicbrainz-docker#120]
thank you. I just updated to the latest commit, copied the ./default/indexer.ini to ./local/indexer.ini, and set the .env to SIR_CONFIG_PATH=./local/indexer.ini

The indexer docker image now won't stay running - the indexer.ini in my local directory has no changes verses the default settings.

**Comment by JoshDi** [comment]
I think you may have updated the DB in another commit. I am recreating my DB and docker images. I will let you know if that fixes the problem

**Comment by yvanzo** [comment]
There is no reason to suspect the DB here. Weird things can occur when the bound file doesn’t exist prior to the creation of the container. I would suggest to try removing the container and creating a new one.

**Comment by JoshDi** [comment]
rebuilding the index docker fixed the problem

**Comment by yvanzo** [comment]
Highlighted the importance of steps order in https://github.com/metabrainz/musicbrainz-docker/commit/985a061c352036511e27223bab88b04b9140961d, because it doesn’t throw any error/warning message otherwise.
