### ISSUE TITLE
error An unexpected error occurred: "https://registry.yarnpkg.com/source-map-url/-/source-map-url-0.4.0.tgz: ESOCKETTIMEDOUT".

### ISSUE THREAD

**Issue by jpbaboo** [metabrainz/musicbrainz-docker#127]
Hi
when i do 
error An unexpected error occurred: "https://registry.yarnpkg.com/source-map-url/-/source-map-url-0.4.0.tgz: ESOCKETTIMEDOUT".

_Step 21/26 : RUN cd /musicbrainz-server/ && yarn install --production &&     eval $( perl -Mlocal::lib) && /musicbrainz-server/script/compile_resources.sh
 ---> Running in c3d21b360ac3
yarn install v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "https://registry.yarnpkg.com/source-map-url/-/source-map-url-0.4.0.tgz: ESOCKETTIMEDOUT".
info If you think this is a bug, please open a bug report with the information provided in "/musicbrainz-server/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
ERROR: Service 'musicbrainz' failed to build: The command '/bin/sh -c cd /musicbrainz-server/ && yarn install --production &&     eval $( perl -Mlocal::lib) && /musicbrainz-server/script/compile_resources.sh' returned a non-zero code: 1_
when i clic on the link

{"code":"ResourceNotFound","message":"/source-map-url/-/source-map-url-0.4.0.tgz: does not exist"}

Thks for your help

**Comment by yvanzo** [comment]
Hi,

* The JSON file https://registry.yarnpkg.com/source-map-url/ shows that `0.4.0` is the latest version.
* When I click on the link https://registry.yarnpkg.com/source-map-url/-/source-map-url-0.4.0.tgz I get the correct file `source-map-url-0.4.0.tgz`.

So it seems that the message _There appears to be trouble with your network connection._ is most probably correct here. The source of these troubles is unknown though. It might be either temporary network issues from yarnpkg.com or temporary network issues from your internet access provider.

**Comment by jpbaboo** [comment]
thks for your answer.. but i have retryed a lot ot times (2 wifi Networks+ Ethernet).. same issue..

info If you think this is a bug, please open a bug report with the information provided in "/musicbrainz-server/yarn-error.log".
With this message.. i don't have the directory /musicbrainz-server/ on my server: UBUNTU19.10

and no file like yarn-error.log..

**Comment by yvanzo** [comment]
The file is in the Docker image being built, but you already provided information it probably contains.

Please check you are able to retrieve https://registry.yarnpkg.com/source-map-url/ and to download https://registry.yarnpkg.com/source-map-url/-/source-map-url-0.4.0.tgz from your browser.

If that does not work, try using a Web proxy as this would likely be a limitation of your internet provider.

**Comment by jpbaboo** [comment]
Thks again for your help
**acces is OK**
{"_id":"source-map-url","_rev":"7-2f032e90f27814b301b77a4275c6b3c0","name":"source-map-url","description":"Tools for working with sourceMappingURL comments.","dist-tags":{"latest":"0.4.0"},"versions":{"0.1.0":{"name":"source-map-url","version":"0.1.0","description":"Tools for working with sourceMappingURL comments.","author":{"name":"Simon Lydell"},"license":"MIT","main":"source-map-url.js","repository":{"type":"git","url":"git://github.com/lydell/source-map-url"},"keywords":["source map","sourceMappingURL","comment","annotation"],"scripts":{"test":"jshint source-map-url.js test/ && mocha"},"devDependencies":{"mocha":"~1.17.1","chai":"~1.9.0","jshint":"~2.4.3"},"testling":{"harness":"mocha","files":"test/*.js","browsers":["ie/8..latest","chrome/latest","firefox/latest","opera/12","opera/latest","safari/5..latest","iphone/6","android-browser/4"]},"bugs":

wget is OK
pi@Lenovo:~/musicbrainz-docker$ sudo wget https://registry.yarnpkg.com/source-map-url/-/source-map-url-0.4.0.tgz
--2020-04-06 14:14:41--  https://registry.yarnpkg.com/source-map-url/-/source-map-url-0.4.0.tgz
Resolving registry.yarnpkg.com (registry.yarnpkg.com)... 104.16.19.35, 104.16.25.35, 104.16.23.35, ...
Connecting to registry.yarnpkg.com (registry.yarnpkg.com)|104.16.19.35|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5406 (5,3K) [application/octet-stream]
Saving to: ‘source-map-url-0.4.0.tgz’

source-map-url-0.4.0.tgz     100%[==============================================>]   5,28K  --.-KB/s    in 0,004s  

2020-04-06 14:14:41 (1,21 MB/s) - ‘source-map-url-0.4.0.tgz’ saved [5406/5406]

so i don't understand!

**Comment by yvanzo** [comment]
@jpbaboo: Which branch `musicbrainz-docker` are you running? [`master`](https://github.com/metabrainz/musicbrainz-docker) or [`mbvm-38-dev`](https://github.com/metabrainz/musicbrainz-docker/tree/mbvm-38-dev)?

**Comment by jpbaboo** [comment]
Hi
i m new on docker/git
this is the link:
https://github.com/metabrainz/musicbrainz-docker

I have installed docker/docker compose as suggested
then 

1. git clone https://github.com/metabrainz/musicbrainz-docker.git
2. cd musicbrainz-docker
3. sudo docker-compose up -d..
and then KO

**Comment by jpbaboo** [comment]
i think there is a problem with  this directory musicbrainz-server.. i can't find it on my server //
Do i have to create it before ? at the root?

ERROR: Service 'musicbrainz' failed to build: The command '/bin/sh -c cd /musicbrainz-server/ && yarn install --production &&     eval $( perl -Mlocal::lib) && /musicbrainz-server/script/compile_resources.sh' returned a non-zero code: 1

**Comment by yvanzo** [comment]
No, it is probably just a network issue, try <del>replacing `yarn install` with `yarn install --network-timeout 300000` (that is 5 minutes) in `musicbrainz-dockerfile/Dockerfile`.</del> (Edit) <ins>using the below commands instead</ins>.

**Comment by yvanzo** [comment]
Also I would recommend you use [`mbvm-38-dev`](https://github.com/metabrainz/musicbrainz-docker/tree/mbvm-38-dev) branch already even though it is at a development stage, it is much more advanced than current `master`. That is completely unrelated to your network issue through.
```shell
git clone --branch mbvm-38-dev https://github.com/metabrainz/musicbrainz-docker.git
cd musicbrainz-docker
sed 's/yarn install/& --network-timeout 300000/' build/musicbrainz/Dockerfile
sudo docker-compose build
```
Follow detailed instructions from the file [README.md](https://github.com/metabrainz/musicbrainz-docker/blob/mbvm-38-dev/README.md).

**Comment by jpbaboo** [comment]
i have a directory pb!!
my work directory is pi@Lenovo:~/musicbrainz-docker
i can't find  a /musicbrainz-dockerfile/Dockerfile ..

**Comment by jpbaboo** [comment]
oups i found it
yarn install --network-timeout 300000
re-run again

**Comment by jpbaboo** [comment]
seems to work!!!!
due to  my slow network traffic..

Thks a lot!!

**Comment by jpbaboo** [comment]
Removing intermediate container 2e3a294b16cb
 ---> 01382633c216
Successfully built 01382633c216
Successfully tagged musicbrainz-docker_musicbrainz:latest
WARNING: Image for service musicbrainz was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating musicbrainz-docker_redis_1  ... done
Creating musicbrainz-docker_search_1  ... done
Creating musicbrainz-docker_db_1     ... done
Creating musicbrainz-docker_indexer_1     ... done
Creating musicbrainz-docker_musicbrainz_1 ... done

Thks again for your help and patience from FRANCE!!
