### ISSUE TITLE
Error building project

### ISSUE THREAD

**Issue by Jerry-27** [metabrainz/musicbrainz-docker#128]
line below didn't work properly
docker-compose run --rm musicbrainz /createdb.sh -fetch

Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"C:/Program Files/Git/createdb.sh\": stat C:/Program Files/Git/createdb.sh: no such file or directory": unknown

**Comment by yvanzo** [comment]
This error seems to be specific to Git for Windows. Its shell is probably replacing `/createdb.sh` with `C:/Program Files/Git/createdb.sh`. Try escaping path with an extra heading slash `/` as follows:
```bash
docker-compose run --rm musicbrainz //createdb.sh -fetch
```

Here is a more general workaround: https://forums.docker.com/t/weird-error-under-git-bash-msys-solved/9210/2

----

Instructions are known to work on GNU/Linux and Mac OS X but feedback from Windows users would be welcome to improve the doc. Also I recommend you to use the development branch [mbvm-38-dev](https://github.com/metabrainz/musicbrainz-docker/tree/mbvm-38-dev).

**Comment by Jerry-27** [comment]
That fixed it.
