### ISSUE TITLE
Issue Building Project

### ISSUE THREAD

**Issue by Jerry-27** [metabrainz/musicbrainz-docker#129]
I ran into the error message below when running " docker-compose run --rm musicbrainz //createdb.sh -fetch " using MusicBrainz Docker: 349a072, Docker Compose: 1.24.1, and Docker Client/Server: 19.03.1/19.03.5.

" Error during CreateTables.sql at /musicbrainz-server/admin/InitDb.pl line 117.
Thu Apr 16 12:03:12 2020 : psql:/musicbrainz-server/admin/sql/CreateTables.sql:15: ERROR:  relation "alternative_release" already exists
Thu Apr 16 12:03:12 2020 : InitDb.pl failed"

**Comment by yvanzo** [comment]
This command cannot be run more than one time, but you can recreate the database (from the data dumps you just downloaded) as follows:

```bash
docker-compose run --rm musicbrainz //recreatedb.sh
```

Default password is `musicbrainz`.

See https://github.com/metabrainz/musicbrainz-docker/tree/mbvm-38-dev#recreate-database

**Comment by Jerry-27** [comment]
Separate but related question. Is this docker image designed to automatically expand like some past musicbrainz instances?  Because the error below(which I ran into) would potentially become a problem with replication turned on.   

"Cannot write: No space left on device"

**Comment by yvanzo** [comment]
The data is stored in docker volumes without any specific limit about occupied space. The limit about docker volumes comes only from your system. You can check where are stored docker volumes with:

```bash
sudo docker volume inspect -f '{{.Mountpoint}}' musicbrainz-docker_pgdata
```

**Comment by Jerry-27** [comment]
After running  " docker-compose up " the server doesn't start up and produces the statement below.

musicbrainz_1  | Argument "Moose::Meta::Method=HASH(0x317fdf0)" isn't numeric in numeric eq (==) at /root/perl5/lib/perl5/MooseX/ABC/Trait/                                                                                                                                    Class.pm line 61.


After running   " winpty docker-compose exec indexer python -m sir reindex "

 File "sir/config.py", line 33, in read_config
    raise ConfigError("No configuration file could be found")
sir.config.ConfigError: No configuration file could be found

**Comment by Jerry-27** [comment]
> The data is stored in docker volumes without any specific limit about occupied space. The limit about docker volumes comes only from your system. You can check where are stored docker volumes with:
> 
> ```shell
> sudo docker volume inspect -f '{{.Mountpoint}}' musicbrainz-docker_pgdata
> ```

To avoid creating a thread marked solved without a listed solution; I followed the stackoverflow instruction below expand the image.  https://stackoverflow.com/a/59390668

**Comment by yvanzo** [comment]
> musicbrainz_1 | Argument "Moose::Meta::Method=HASH(0x317fdf0)" isn't numeric in numeric eq (==) at /root/perl5/lib/perl5/MooseX/ABC/Trait/ Class.pm line 61.

You can safely ignore these warnings.

> File "sir/config.py", line 33, in read_config
> raise ConfigError("No configuration file could be found")
> sir.config.ConfigError: No configuration file could be found

The configuration file `config.ini` has probably not been mounted correctly, you can gather more info about current parameters with:

```bash
docker inspect  -f '{{.Mounts}}' musicbrainz-docker_indexer_1
```

**Comment by Jerry-27** [comment]
Is this correct?

[{bind  /d/musicbrainz/musicbrainz-docker/default/indexer.ini /code/config.ini  rw true rprivate}]

**Comment by yvanzo** [comment]
Yes, it is. Try rebuilding the image for this service as follows:
```bash
docker-compose rm --stop indexer
docker-compose build --no-cache indexer
docker-compose up -d
```

**Comment by Jerry-27** [comment]
I still received the same error after rebuilding the indexer.
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/code/sir/__main__.py", line 127, in <module>
    main()
  File "/code/sir/__main__.py", line 116, in main
    config.read_config()
  File "sir/config.py", line 33, in read_config
    raise ConfigError("No configuration file could be found")
sir.config.ConfigError: No configuration file could be found
```

**Comment by yvanzo** [comment]
Ok, it might be that Docker for Windows doesn’t correctly handle bind mounts having path starting with `/d/`. You can change it by setting the variable `SIR_CONFIG_PATH` in your file `.env`. I’m not sure of the syntax to be adopted yet. Try something like:

```ini
SIR_CONFIG_PATH=D:\musicbrainz\musicbrainz-docker\default\indexer.ini
```

You can check if that works with:

```bash
winpty docker-compose restart indexer
winpty docker-compose exec indexer ls -l //code/config.ini
```

It should return like this (but hashed values):
```
-rw-r--r-- 1 1000 985 ### ### ## ##:## //code/config.ini
```

**Comment by Jerry-27** [comment]
Adding the variable partially worked. The steps I followed are below.

- Add the shared folder path ``` D:\musicbrainz```  named ```musicbrainz``` to the default virtual box instance following the instruction here ```https://stackoverflow.com/a/52661380```
- Create a variable ```SIR_CONFIG_PATH=/musicbrainz/musicbrainz-docker/default/indexer.ini``` in the ```.env``` file.

- Restarted indexer  
` winpty docker-compose restart indexer`
`winpty docker-compose exec indexer ls -l //code/config.ini 
`

- Ran ` winpty docker-compose exec indexer python -m sir reindex` and now see 
`2020-04-18 19:47:52,737: Checking whether the versions of the Solr cores are supported`
`2020-04-18 19:47:54,248: Importing annotation...`

Hopefully this finishes in 4 hours. Thank you for your help 😄

**Comment by Jerry-27** [comment]
" admin/create-amqp-extension "

groups: cannot find name for group ID 197121
groups: cannot find name for group ID 197121
create-amqp-extension: cannot set docker command: please either
admin/lib/common.inc.bash: line 30: USER: unbound variable

**Comment by yvanzo** [comment]
It seems that Windows specifics must be added to `admin/lib/common.inc.bash`. So that I can try to patch scripts and update documentation accordingly,can you please summarize what you installed (Git for Windows I guess), configured, and how?

A few more questions:
1.  How are you running commands?
     1. Using `winpty` as a prefix to all/some/which commands?
     2. Using double-slash `//` at the beginning of every path?
     3. Using `export MSYS_NO_PATHCONV=1`?
2. Does this return `msys`?
    ```bash
    echo $OSTYPE # edit
    ```
3. What does this return?
    ```bash
    groups 2>/dev/null
    ```

Thank you!

**Comment by Jerry-27** [comment]
> Using winpty as a prefix to all/some/which commands?  

Yes for some. Whenever a command fails and it's suggested by the command line. I double checked this by running ` winpty docker-compose restart indexer` vs `docker-compose restart indexer` both worked so I'm not sure what's going on there.

> Using double-slash // at the beginning of every path?  

Yes. Every time a command requires a specific file to be run such as `docker-compose run --rm musicbrainz //createdb.sh`

> Does this return msys? ` echo $OSTYPE`  

 Without the underscore, yes.

> What does this return?  

 `197121`   after running the command.
 
I'm using the tools below.
`docker toolbox`
`MINGW64`

**Comment by yvanzo** [comment]
> " admin/create-amqp-extension "
> 
> groups: cannot find name for group ID 197121
> groups: cannot find name for group ID 197121
> create-amqp-extension: cannot set docker command: please either
> admin/lib/common.inc.bash: line 30: USER: unbound variable

These errors should be solved with commit https://github.com/metabrainz/musicbrainz-docker/pull/133/commits/c2ea55bc4e73db84e37e74e626f111ecd19e5d6f of draft pull request https://github.com/metabrainz/musicbrainz-docker/pull/133 you can test by using the branch [`msys`](https://github.com/metabrainz/musicbrainz-docker/tree/msys). Other errors will most probably occur. It may require more tweaks because of path expansion, using either `MSYS_NO_PATHCONV=1` or `winpty` sometimes.

Note about pull request https://github.com/metabrainz/musicbrainz-docker/pull/133: Since I’m not using Windows myself, I cannot complete it on my own, especially the parts about requirements and instructions. Proposing changes to [`README.md`@`msys`](https://github.com/metabrainz/musicbrainz-docker/blob/msys/README.md) (using the pencil at the top right) would be very welcome.

**Comment by yvanzo** [comment]
Sorry but I can definitely not fix every upcoming issue on Windows as I’m not actually using it. None of our team is. None of our projects (but Picard) supports it either. We will probably just add “Linux / Mac OS X” to requirements.

I can only recommend you to use Ubuntu via VirtualBox on Windows as a Docker host instead.

If you really want it to make it work with Docker on Windows, volunteers are welcome to, and I added more references in comment to #133, but it probably requires to invest a lot of time!

Note: It is also possible to run commands directly instead of using `admin/` helper scripts, but it most probably requires to invest a lot of time too because of the complexity of the project running 6 services.

**Comment by Jerry-27** [comment]
> Sorry but I can definitely not fix every upcoming issue on Windows as I’m not actually using it. None of our team is. None of our projects (but Picard) supports it either. We will probably just add “Linux / Mac OS X” to requirements.

understandable

> I can only recommend you to use Ubuntu via VirtualBox on Windows as a Docker host instead.

I was under the impression that was how the docker-toolbox worked.

**Comment by yvanzo** [comment]
> > I can only recommend you to use Ubuntu via VirtualBox on Windows as a Docker host instead.
> 
> I was under the impression that was how the docker-toolbox worked.

Yes, it is, it uses MobyLinux image (which I don’t know how it compares to Ubuntu image, might be based on it). I will continue to help you with any question you have but I cannot test anything here.

If you switch to another virtual machine, https://docs.docker.com/docker-for-windows/docker-toolbox/ shows how to move data from Docker Toolbox to Docker Desktop so it should be possible to move data from a virtual machine to another.

**Comment by yvanzo** [comment]
> We will probably just add “Linux / Mac OS X” to requirements.

Done now with #133, see [Required sofware](https://github.com/metabrainz/musicbrainz-docker/tree/mbvm-38-dev#required-software).

I also created MBVM-53 to summarize research that has been done to run on Windows so far.

**Comment by Jerry-27** [comment]
The statement below was added to the `.env` file after running admin/set-replication-token. Is the purpose of the statement to reference both .yml files on disk? After trying to bring up the container I'm running into an invalid argument error.

` COMPOSE_FILE=docker-compose.yml:compose/replication-token.yml `

**Comment by yvanzo** [comment]
> Is the purpose of the statement to reference both .yml files on disk?

Yes

See https://docs.docker.com/compose/reference/envvars/#compose_file
from https://docs.docker.com/compose/environment-variables/#configure-compose-using-environment-variables
from https://github.com/metabrainz/musicbrainz-docker/tree/mbvm-38-dev#docker-environment-variables

> After trying to bring up the container I'm running into an invalid argument error.

Might it be a path issue again? Run `docker-compose config` to see how it is interpreted.

**Comment by yvanzo** [comment]
Just curious, did you figure out to make it work with your setup/for your needs?

I started to remove unneeded paths such as script’s path in commit https://github.com/metabrainz/musicbrainz-docker/commit/2a674245b603f7e2a786bcea28a9745f39083d0c.
