### ISSUE TITLE
Create variables that allow for an external postgres database to be used (instead of linking the containers together)

### ISSUE THREAD

**Issue by monksy** [metabrainz/musicbrainz-docker#13]
At the moment I have an external db that I would like to use instead of one built into the docker container. I would like to stand up an instance of musicbrainz without having to stand up another instance of postgres on the same server.

**Comment by jsturgis** [comment]
You could change the DBDefs.pm and set these vars to point to your postgresql instance:

```
        username    => "$ENV{DB_ENV_POSTGRES_USER}",
        password        => "$ENV{DB_ENV_POSTGRES_PASSWORD}",
        host            => "$ENV{DB_PORT_5432_TCP_ADDR}",
        port            => "$ENV{DB_PORT_5432_TCP_PORT}",
```

Then remove the postgresql service and remove the link to postgresql from the docker-compose.yml file.

**Comment by jsturgis** [comment]
Closing this, if my suggestion doesn't work please reopen.
