### ISSUE TITLE
how to just update the index rather than recreate it?

### ISSUE THREAD

**Issue by gresbtim** [metabrainz/musicbrainz-docker#136]
seems that after the daily cron the indexes are not updated.

**Comment by yvanzo** [comment]
Hi, this is not possible with the old search server in the legacy branch `master`. But this can be done with the development branch [`mbvm-38-dev`](https://github.com/metabrainz/musicbrainz-docker/tree/mbvm-38-dev) which is stable enough now and will be merged to `master` soon. Just check out that branch and follow instructions.

**Comment by yvanzo** [comment]
That development branch has been merged into `master`. See release notes starting with `v-2020-05-14-solr7` at <https://github.com/metabrainz/musicbrainz-docker/releases>.
Please note that live indexing is still an experimental feature for slave servers.
