### ISSUE TITLE
Cannot Rebuild Latest 

### ISSUE THREAD

**Issue by JoshDi** [metabrainz/musicbrainz-docker#143]
I am having issues rebuilding my musicbrainz server on the mbvm-38-dev branch. When I try to run "sudo docker-compose build" 

I get the following errors and cannot build. Any ideas? 

`Step 8/20 : ARG MUSICBRAINZ_SERVER_VERSION=v-2020-04-27
 ---> Running in ea45b372180c
Removing intermediate container ea45b372180c
 ---> 564f64c24bf0
Step 9/20 : RUN git clone --depth=1 --branch $MUSICBRAINZ_SERVER_VERSION https://github.com/metabrainz/musicbrainz-server.git musicbrainz-server
 ---> Running in 09bf3fd512f4
Cloning into 'musicbrainz-server'...
Note: checking out '8ad15d7222d38260b88774a373da56efee2bed91'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

Removing intermediate container 09bf3fd512f4
 ---> 1941a62cc70a
Step 10/20 : WORKDIR /musicbrainz-server
 ---> Running in f0610126e538
Removing intermediate container f0610126e538
 ---> 17ddae6db774
Step 11/20 : ARG NODE_VERSION=10.19.0
 ---> Running in 166f3f398575
Removing intermediate container 166f3f398575
 ---> 600551d1a1ae
Step 12/20 : RUN cp docker/yarn_pubkey.txt /tmp &&     cd /tmp &&     apt-key add yarn_pubkey.txt &&     declare i=5 && while true; do         apt-key adv --keyserver hkps.pool.sks-keyservers.net --refresh-keys Yarn &&         break || echo "apk-key failed with exit status '$?'";         i=$((i - 1)); [[ $i -gt 0 ]] && echo "retrying..." || exit 1;     done && unset i &&     echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list &&     apt-get update -o Dir::Etc::sourcelist="sources.list.d/yarn.list" -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0" &&     curl -sSLO --retry 5 https://deb.nodesource.com/node_10.x/pool/main/n/nodejs/nodejs_$NODE_VERSION-1nodesource1_amd64.deb &&     dpkg -i nodejs_$NODE_VERSION-1nodesource1_amd64.deb &&     apt-get purge -qy cmdtest &&     apt-get install --no-install-recommends -qy         yarn &&     rm /tmp/* &&     rm -rf /var/lib/apt/lists/*
 ---> Running in b8a579066e7c
OK
Executing: /tmp/tmp.p9AT3LrUOJ/gpg.1.sh --keyserver
hkps.pool.sks-keyservers.net
--refresh-keys
Yarn
gpg: refreshing 1 key from hkp://hkps.pool.sks-keyservers.net
gpg: requesting key 86E50310 from hkp server hkps.pool.sks-keyservers.net
gpgkeys: key 72ECF46A56B4AD39C907BBB71646B01B86E50310 can't be retrieved
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
gpg: keyserver communications error: keyserver helper general error
gpg: keyserver communications error: unknown pubkey algorithm
gpg: keyserver refresh failed: unknown pubkey algorithm
apk-key failed with exit status '2'
retrying...
Executing: /tmp/tmp.vVcJz7FBYm/gpg.1.sh --keyserver
hkps.pool.sks-keyservers.net
--refresh-keys
Yarn
gpg: refreshing 1 key from hkp://hkps.pool.sks-keyservers.net
gpg: requesting key 86E50310 from hkp server hkps.pool.sks-keyservers.net
gpgkeys: key 72ECF46A56B4AD39C907BBB71646B01B86E50310 can't be retrieved
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
gpg: keyserver communications error: keyserver helper general error
gpg: keyserver communications error: unknown pubkey algorithm
gpg: keyserver refresh failed: unknown pubkey algorithm
apk-key failed with exit status '2'
retrying...
Executing: /tmp/tmp.yXzSPUGOXR/gpg.1.sh --keyserver
hkps.pool.sks-keyservers.net
--refresh-keys
Yarn
gpg: refreshing 1 key from hkp://hkps.pool.sks-keyservers.net
gpg: requesting key 86E50310 from hkp server hkps.pool.sks-keyservers.net
gpgkeys: key 72ECF46A56B4AD39C907BBB71646B01B86E50310 can't be retrieved
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
gpg: keyserver communications error: keyserver helper general error
gpg: keyserver communications error: unknown pubkey algorithm
gpg: keyserver refresh failed: unknown pubkey algorithm
apk-key failed with exit status '2'
retrying...
Executing: /tmp/tmp.WyCaFmOFUb/gpg.1.sh --keyserver
hkps.pool.sks-keyservers.net
--refresh-keys
Yarn
gpg: refreshing 1 key from hkp://hkps.pool.sks-keyservers.net
gpg: requesting key 86E50310 from hkp server hkps.pool.sks-keyservers.net
gpgkeys: key 72ECF46A56B4AD39C907BBB71646B01B86E50310 can't be retrieved
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
gpg: keyserver communications error: keyserver helper general error
gpg: keyserver communications error: unknown pubkey algorithm
gpg: keyserver refresh failed: unknown pubkey algorithm
apk-key failed with exit status '2'
retrying...
Executing: /tmp/tmp.hasC82gcPh/gpg.1.sh --keyserver
hkps.pool.sks-keyservers.net
--refresh-keys
Yarn
gpg: refreshing 1 key from hkp://hkps.pool.sks-keyservers.net
gpg: requesting key 86E50310 from hkp server hkps.pool.sks-keyservers.net
gpgkeys: key 72ECF46A56B4AD39C907BBB71646B01B86E50310 can't be retrieved
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
gpg: keyserver communications error: keyserver helper general error
gpg: keyserver communications error: unknown pubkey algorithm
gpg: keyserver refresh failed: unknown pubkey algorithm
apk-key failed with exit status '2'
ERROR: Service 'musicbrainz' failed to build: The command '/bin/bash -o pipefail -c cp docker/yarn_pubkey.txt /tmp &&     cd /tmp &&     apt-key add yarn_pubkey.txt &&     declare i=5 && while true; do         apt-key adv --keyserver hkps.pool.sks-keyservers.net --refresh-keys Yarn &&         break || echo "apk-key failed with exit status '$?'";         i=$((i - 1)); [[ $i -gt 0 ]] && echo "retrying..." || exit 1;     done && unset i &&     echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list &&     apt-get update -o Dir::Etc::sourcelist="sources.list.d/yarn.list" -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0" &&     curl -sSLO --retry 5 https://deb.nodesource.com/node_10.x/pool/main/n/nodejs/nodejs_$NODE_VERSION-1nodesource1_amd64.deb &&     dpkg -i nodejs_$NODE_VERSION-1nodesource1_amd64.deb &&     apt-get purge -qy cmdtest &&     apt-get install --no-install-recommends -qy         yarn &&     rm /tmp/* &&     rm -rf /var/lib/apt/lists/*' returned a non-zero code: 1
`

**Comment by yvanzo** [comment]
This error occurs when the key server is not available. You can just try it again for now.
I will look into a more reliable way to retrieve PGP keys.

**Comment by JoshDi** [comment]
Thank you. Just  tried again and I am still getting issues: 

```
Executing: /tmp/tmp.CUsQVASAp6/gpg.1.sh --keyserver
hkps.pool.sks-keyservers.net
--refresh-keys
Yarn
gpg: refreshing 1 key from hkp://hkps.pool.sks-keyservers.net
gpg: requesting key 86E50310 from hkp server hkps.pool.sks-keyservers.net
gpgkeys: key 72ECF46A56B4AD39C907BBB71646B01B86E50310 can't be retrieved
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
gpg: keyserver communications error: keyserver helper general error
gpg: keyserver communications error: unknown pubkey algorithm
gpg: keyserver refresh failed: unknown pubkey algorithm
apk-key failed with exit status '2'
```

**Comment by yvanzo** [comment]
Try replacing

> `hkps.pool.sks-keyservers.net`

with

> `hkp://p80.pool.sks-keyservers.net:80`

in `build/musicbrainz/Dockerfile`.

**Comment by JoshDi** [comment]
that fixed it. thanks

**Comment by yvanzo** [comment]
Fixed with linked pull request.
