### ISSUE TITLE
Something wrong with nginx setup/musicbrainz webui

### ISSUE THREAD

**Issue by orangepeelbeef** [metabrainz/musicbrainz-docker#15]
links in the musicbrainz site point to /static/build  which is not a valid directory so css and scripts are not loading for the musicbrainz webui

/static/build 404's from nginx

**Comment by jsturgis** [comment]
sounds like the resources never got built.

**Comment by jsturgis** [comment]
@orangepeelbeef can you run this command and see if anything is found?
`sudo docker exec CONTAINER_ID ls /musicbrainz-server/root/static/build`

**Comment by orangepeelbeef** [comment]
ls: cannot access '/musicbrainz-server/root/static/build': No such file or directory

**Comment by jsturgis** [comment]
Thanks for letting me know about these issues, everything should be working now but let me know if you have any other problems.
