### ISSUE TITLE
Replication Issue with Latest Musicbrainz Docker

### ISSUE THREAD

**Issue by JoshDi** [metabrainz/musicbrainz-docker#154]
I have added my replication token properly, but based on the latest master commit (da0248a) replication crons do not work properly. 

```
root@HTPC-Xeon:/storage/musicbrainz-docker# docker-compose exec musicbrainz replication.sh &
[1] 24925
root@HTPC-Xeon:/storage/musicbrainz-docker# docker-compose exec musicbrainz /usr/bin/tail -f slave.log
Invalid or missing REPLICATION_ACCESS_TOKEN in DBDefs.pm -- get one at https://metabrainz.org at ./admin/replication/LoadReplicationChanges line 116.
```

```
root@HTPC-Xeon:/storage/musicbrainz-docker# cat .env
MUSICBRAINZ_WEB_SERVER_HOST=192.168.1.40
MUSICBRAINZ_CRONTAB_PATH=./local/replication.cron
SIR_CONFIG_PATH=./local/indexer.ini
COMPOSE_FILE=docker-compose.yml:local/compose/memory-settings.yml:compose/publishing-all-ports.yml:compose/live-indexing-search.yml:compose/replication-token.yml
```

```
root@HTPC-Xeon:/storage/musicbrainz-docker/local/secrets# ls
metabrainz_access_token
```

**Comment by yvanzo** [comment]
Please check the file is mounted at  `/run/secrets/metabrainz_access_token` and has 40 characters:

```bash
docker-compose exec musicbrainz ls -l /run/secrets
docker-compose exec musicbrainz wc -m /run/secrets/metabrainz_access_token
```

**Comment by JoshDi** [comment]
Looks like the file isn't mounted in the container. My replication token hasn't changed in 6 months and seems to be 40 characters. 

```
root@HTPC-Xeon:/storage/musicbrainz-docker# docker-compose exec musicbrainz wc -m /run/secrets/metabrainz_access_token
wc: /run/secrets/metabrainz_access_token: No such file or directory
root@HTPC-Xeon:/storage/musicbrainz-docker# wc -m local/secrets/metabrainz_access_token
41 local/secrets/metabrainz_access_token
root@HTPC-Xeon:/storage/musicbrainz-docker#
```

**Comment by JoshDi** [comment]
Ok so I rewrote my metabrainz access token and reran **docker-compose up -d**

```
root@HTPC-Xeon:/storage/musicbrainz-docker# docker-compose exec musicbrainz ls -l /run/secrets
total 4
-rw------- 1 root root 41 Jun  1 16:24 metabrainz_access_token
root@HTPC-Xeon:/storage/musicbrainz-docker# docker-compose exec musicbrainz wc -m /run/secrets/metabrainz_access_token
41 /run/secrets/metabrainz_access_token
```

The file is there now so I try to run replication:
```
root@HTPC-Xeon:/storage/musicbrainz-docker# docker-compose exec musicbrainz replication.sh &
[1] 21496
root@HTPC-Xeon:/storage/musicbrainz-docker# docker-compose exec musicbrainz /usr/bin/tail -f slave.log
Mon Jun  1 16:30:35 2020 : Continuing a previously aborted load
Mon Jun  1 16:30:35 2020 : Processing replication changes
WARNING:  SET TRANSACTION can only be used in transaction blocks
WARNING:  SET CONSTRAINTS can only be used in transaction blocks
     XIDs     Stmts est%  XIDs/sec  Stmt/sec
        0         0   0%         0         0WARNING:  amqp[mq:5672] login failed on broker 1
WARNING:  amqp[mq:5672] login failed on broker 1
        1         2   0%         0         0WARNING:  amqp[mq:5672] login failed on broker 1
WARNING:  amqp[mq:5672] login failed on broker 1
        2         4   0%         0         0
```

This looks similar to my issues in #150 and #153

**Comment by yvanzo** [comment]
Ok, please check the `amqp` extension to PosgreSQL is correctly loaded:

```bash
docker-compose exec db psql -U musicbrainz -d musicbrainz_db -c '\dx'
```

**Comment by JoshDi** [comment]
Sure, here you go:

`root@HTPC-Xeon:/storage/musicbrainz-docker# docker-compose exec indexer python -m sir amqp_setup
2020-06-01 17:47:27,574: Connecting to RabbitMQ
2020-06-01 17:47:27,584: Declaring exchanes
2020-06-01 17:47:27,587: Declaring queues
2020-06-01 17:47:27,595: Binding queues
2020-06-01 17:47:27,600: Done
root@HTPC-Xeon:/storage/musicbrainz-docker# admin/create-amqp-extension
Installing indexer AMQP extension into PostgreSQL ...
BEGIN
CREATE EXTENSION
ALTER SCHEMA
ALTER TABLE
INSERT 0 1
COMMIT
Successfully created amqp extension in the database.
root@HTPC-Xeon:/storage/musicbrainz-docker# admin/setup-amqp-triggers clean
Cleaning indexer triggers install/uninstall scripts up ...
Done.
root@HTPC-Xeon:/storage/musicbrainz-docker# admin/setup-amqp-triggers install
Installing indexer triggers ...
BEGIN
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
COMMIT
BEGIN
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
COMMIT
Regenerating SQL scripts in /tmp/indexer-sql/...
Could not find CreateTables.sql, search_path might not be correct
Could not find CreateTables.sql, skipping
Could not find CreateIndexes.sql, skipping
Could not find CreateSearchIndexes.sql, skipping
Could not find CreateReplicationTriggers.sql, skipping
Done.


root@HTPC-Xeon:/storage/musicbrainz-docker# docker-compose exec db psql -U musicbrainz -d musicbrainz_db -c '\dx'
                                    List of installed extensions
     Name      | Version |   Schema   |                         Description
---------------+---------+------------+--------------------------------------------------------------
 amqp          | 0.4.1   | amqp       | AMQP protocol support for PostgreSQL
 cube          | 1.4     | public     | data type for multidimensional cubes
 earthdistance | 1.1     | public     | calculate great-circle distances on the surface of the Earth
 plpgsql       | 1.0     | pg_catalog | PL/pgSQL procedural language
 unaccent      | 1.1     | public     | text search dictionary that removes accents
(5 rows)

`

**Comment by yvanzo** [comment]
If the issue is not in `db`, it might be in `mq`. Please check `/search-index-rebuilder` virtual host:

```bash
docker-compose exec mq rabbitmqadmin list vhosts
```

If it is not there, try to recreate the container for `mq`:
```bash
docker-compose up --force-recreate -d mq
```

**Comment by JoshDi** [comment]
It looks like the vhost is there:

```
root@HTPC-Xeon:/storage/musicbrainz-docker# docker-compose exec mq rabbitmqadmin list vhosts
+-------------------------+----------+
|          name           | messages |
+-------------------------+----------+
| /                       |          |
| /search-index-rebuilder |          |
+-------------------------+----------+
```


I tried starting over by deleting all of my docker images, containers, volumes, etc.

When running **docker-compose run --rm musicbrainz createdb.sh -fetch** I get an error loading the DB. I can get the DB to populate correctly by running **docker-compose run --rm musicbrainz recreatedb.sh** 

I then ran replication once to get my slave DB up to date.
```
sudo docker-compose exec musicbrainz replication.sh &
sudo docker-compose exec musicbrainz /usr/bin/tail -f slave.log
```

I then re-ran indexing once:
`docker-compose exec indexer python -m sir reindex`

Lastly, I enabled live indexing:
```
sudo docker-compose exec indexer python -m sir amqp_setup
admin/create-amqp-extension
admin/setup-amqp-triggers install
```

I checked to see that the Index and DB match:
```
root@HTPC-Xeon:/storage/musicbrainz-docker/admin# ./check-search-indexes all
CORE           STATUS  INDEX     DB
editor         OK      0         /0
instrument     OK      994       /994
series         OK      11517     /11517
place          OK      41506     /41506
event          OK      42259     /42259
tag            OK      98284     /98284
area           OK      118171    /118171
label          OK      180549    /180549
cdstub         OK      293271    /293271
annotation     OK      360209    /360209
work           OK      1319385   /1319385
artist         OK      1654937   /1654937
release-group  OK      2004433   /2004433
release        OK      2536886   /2536886
url            OK      6702340   /6702340
recording      OK      22567115  /22567115
```

Now if I kick off another replication job, I get the mq login issues again:
```
root@HTPC-Xeon:/storage/musicbrainz-docker/admin# docker-compose exec musicbrainz replication.sh &
[1] 32935
root@HTPC-Xeon:/storage/musicbrainz-docker/admin# docker-compose exec musicbrainz /usr/bin/tail -f slave.log
Mon Jun  1 20:31:15 2020 : load dbmirror_pendingdata
dbmirror_pendingdata               16392 100%    667698 0.02 sec
Mon Jun  1 20:31:15 2020 : import finished
Loaded 2 tables (27434 rows) in 0 seconds
Mon Jun  1 20:31:15 2020 : Removing /tmp/loadrep-_LGz74
Mon Jun  1 20:31:15 2020 : Processing replication changes
WARNING:  SET TRANSACTION can only be used in transaction blocks
WARNING:  SET CONSTRAINTS can only be used in transaction blocks
     XIDs     Stmts est%  XIDs/sec  Stmt/sec
        0         0   0%         0         0WARNING:  amqp[mq:5672] login failed on broker 1
        1         2   0%         0         0WARNING:  amqp[mq:5672] login failed on broker 1
WARNING:  amqp[mq:5672] login failed on broker 1
WARNING:  amqp[mq:5672] login failed on broker 1
        2         6   0%         0         0WARNING:  amqp[mq:5672] login failed on broker 1
        3         7   0%         0         0WARNING:  amqp[mq:5672] login failed on broker 1
WARNING:  amqp[mq:5672] login failed on broker 1
```

**Comment by mwiencek** [comment]
That's because rabbitmq 3.6.16 decreased channel_max to 2048, but musicbrainz-docker is only using pg_amqp 0.4.1 which doesn't have https://github.com/omniti-labs/pg_amqp/commit/39b76198f40547dea090fc03e31c4321c07ee9bc. If you check the docker logs for rabbitmq it should log errors about that. pg_amqp must be ugpraded to 0.4.2 in musicbrainz-docker.

**Comment by yvanzo** [comment]
Thanks for finding the real issue. There is no version `0.4.2` still, instead I pinned `pg_amqp` to the commit [`240d477`](https://github.com/omniti-labs/pg_amqp/commit/240d477d40c5e7a579b931c98eb29cef4edda164) which is the latest `master` commit and the one that was used before the previous release of `musicbrainz-docker`. See commit https://github.com/metabrainz/musicbrainz-docker/commit/3164d30627306f7deb688ab1cdc075cf64b9401d. This is available in [`v-2020-06-02`](https://github.com/metabrainz/musicbrainz-docker/releases/tag/v-2020-06-02).

**Comment by JoshDi** [comment]
Thank you, @mwiencek and @yvanzo! 

Live indexing now works again

**Comment by mwiencek** [comment]
Thanks @yvanzo too. Good to hear it's working. I wasn't able to test that myself, I just remembered running into the same issue with my local setup some months ago & then checked what versions musicbrainz-docker had.
