### ISSUE TITLE
Error When Creating Database

### ISSUE THREAD

**Issue by Jerry-27** [metabrainz/musicbrainz-docker#170]
Encountered the error below when running `sudo docker-compose run --rm musicbrainz createdb.sh -fetch` in Ubuntu running in virtual box.

Musicbrainz Docker: v-2020-08-24
Docker Compose: 1.26.2
Docker Client/Server: 19.03.8/19.03.8

" DBI connect('dbname=template1;host=db;port=5432','musicbrainz',...) failed: could not translate host name "db" to address: Name or service not known "

**Comment by RillingDev** [comment]
Facing same issue on a Debian 10 VM
Musicbrainz Docker:v-2020-11-02
Docker Compose: 1.21.0
Docker Client/Server: 18.09.1,
