### ISSUE TITLE
Live Indexing Issue When Upgrading to v-2020-11-02

### ISSUE THREAD

**Issue by JoshDi** [metabrainz/musicbrainz-docker#175]
After upgrading to v-2020-11-02, or any other release, I typically have to run **sudo docker-compose exec indexer python -m sir amqp_setup** to get live indexing to work properly. Should we add these to the upgrade instructions or can you make this a part of the script? Thank you!

**Comment by yvanzo** [comment]
It is likely the same issue as MBVM-69 which is resolved with today’s release [v-2021-05-03](https://github.com/metabrainz/musicbrainz-docker/releases/tag/v-2021-05-03).
