### ISSUE TITLE
CSS not loading on webserver

### ISSUE THREAD

**Issue by greengeek** [metabrainz/musicbrainz-docker#177]
Please report issues to the most appropriate project and component at
https://tickets.metabrainz.org

For informal discussions, simply join MetaBrainz community forums at
https://community.metabrainz.org

For instant chat about development, join #metabrainz IRC channel at
irc://irc.freenode.net/metabrainz

I just followed these instructions and I am able to access the webserver at http://my-ip-address:5000  however the page shows up with no styling.  I brought up the browser debugger and found that the css file can not be found.  Other than missing styling and logos, everything else appears to be working at first glance. I verified this on multiple systems and with different browsers, both firefox and chrome. 

Also on a side note, I then decided to go the long route and do a full build of the musicbrainz server found at https://github.com/metabrainz/musicbrainz-server/blob/master/INSTALL.md   It also has the same issue.

**Comment by PeterCodar** [comment]
Maybe the issue [#55](https://github.com/metabrainz/musicbrainz-docker/issues/55) can help you?

**Comment by greengeek** [comment]
Thank you.  I will have to check for that variable.  I had changed MUSICBRAINZ_WEB_SERVER_HOST and MUSICBRAINZ_WEB_SERVER_PORT as per the instructions, but I didn't see or notice a WEB_SERVER variable.

**Comment by greengeek** [comment]
I got it to work using the above information as a starting point.  Here is what I did in case anyone in the future runs across the same issue.

Change directory to /musicbrainz-docker
edit the hidden file .env
add the line:

`MUSICBRAINZ_WEB_SERVER_HOST=1.1.1.127`

change 1.1.1.127 to whatever your server IP is.

You can verify the value is being passed by typing:
`sudo docker-compose config`

Next update the container to use this change by typing:
`sudo docker-compose build`

Finally start back up your server by typing:
`sudo docker-compose up -d`
