### ISSUE TITLE
update to postgres 9.5

### ISSUE THREAD

**Issue by orangepeelbeef** [metabrainz/musicbrainz-docker#18]
Latest replication data requires migration to postgres 9.5    

(and i just got it all working too   _le sigh_ )

**Comment by orangepeelbeef** [comment]
https://github.com/jsturgis/musicbrainz-docker/pull/19

**Comment by orangepeelbeef** [comment]
Hrm, I tried #20 but something seems to be off, the database does not appear to be starting.
Same thing happened on my PR though.

md5sum: WARNING: 3 listed files could not be read
Failed query:
        'SELECT version();'
        ()
08006 DBI connect('dbname=template1;host=172.17.0.4;port=5432','musicbrainz',...) failed: could not connect to server: Connection refused
        Is the server running on host "172.17.0.4" and accepting
        TCP/IP connections on port 5432?
 at /musicbrainz-server/admin/../lib/Sql.pm line 460.
        Sql::catch {...} (MusicBrainz::Server::Exceptions::DatabaseError=HASH(0x3d8eb48)) called at /usr/share/perl5/Try/Tiny.pm line 115
        Try::Tiny::try(CODE(0x3606800), Try::Tiny::Catch=REF(0x3c4b208), Try::Tiny::Finally=REF(0x16b76b0)) called at /musicbrainz-server/admin/../lib/Sql.pm line 466
        Sql::_select_list(Sql=HASH(0x35fcc18), "SELECT version();", ARRAY(0x3b71c30), "arrayref", CODE(0x3b71af8)) called at /musicbrainz-server/admin/../lib/Sql.pm line 485
        Sql::select_list_of_lists(Sql=HASH(0x35fcc18), "SELECT version();") called at /musicbrainz-server/admin/../lib/Sql.pm line 416
        Sql::select_single_column_array(Sql=HASH(0x35fcc18), "SELECT version();") called at /musicbrainz-server/admin/../lib/Sql.pm line 431
        Sql::select_single_value(Sql=HASH(0x35fcc18), "SELECT version();") called at /musicbrainz-server/admin/InitDb.pl line 74
        main::RequireMinimumPostgreSQLVersion() called at /musicbrainz-server/admin/InitDb.pl line 529
08006 DBI connect('dbname=template1;host=172.17.0.4;port=5432','musicbrainz',...) failed: could not connect to server: Connection refused
        Is the server running on host "172.17.0.4" and accepting
        TCP/IP connections on port 5432?

**Comment by orangepeelbeef** [comment]
sudo docker run -it musicbrainzdocker_postgresql /bin/bash

root@9cb9ce645771:/etc/init.d# service postgresql start
[warn] No PostgreSQL clusters exist; see "man pg_createcluster" ... (warning).

**Comment by orangepeelbeef** [comment]
i get the same behavior starting a fresh postgres 9.5 docker image :/

**Comment by orangepeelbeef** [comment]
Ooops I did not mean to close

**Comment by jsturgis** [comment]
I am currently importing the DB dumps into 9.5, did you delete the old images and rebuild?

**Comment by orangepeelbeef** [comment]
i did a no-cache build, i'll trash all the images and try again.

**Comment by orangepeelbeef** [comment]
Must have been the image, looking good.
