### ISSUE TITLE
Musicbrainz docker behind nginx reverse proxy

### ISSUE THREAD

**Issue by myopenflixr** [metabrainz/musicbrainz-docker#182]
Hello,

I have successfully installed Musicbrainz docker on a VM and i am able to access it perfectly at http://localip:5000.

My question is, what changes would need to be made to be able to access via Ngninx Reverse Proxy at https://musicbrainz.myhost.com

I manually added the following to my .env file:
MUSICBRAINZ_WEB_SERVER_HOST=musicbrainz.myhost.com
MUSICBRAINZ_USE_PROXY=1

However, musicbrainz is still wanting to use port 5000 on all url references. For example, when I navigate to https://musicbrainz.myhost.com, I loose all css styling. And it's trying to pull the header logo from https://musicbrainz.myhost.com:5000/static/build/header-logo-791fb3f.svg

Is there a way to prevent musicbrainz from inserting the port # in the URLS's? Or is there a way to have nginx strip the port # from the url?

I have tried so many different combinations within nginx to get this to work without any luck.

I have MULTIPLE other services running behind nginx with zero issues. It's just musicbrainz that I cannot get figured out.

Thank You,
Mike

**Comment by yvanzo** [comment]
Hi Mike,

I hope answered your question on community forums at <https://community.metabrainz.org/t/custom-url-with-musicbrainz-docker/514402>.

You are welcome!

**Comment by myopenflixr** [comment]
@yvanzo , that seemed to do the trick! I manually added your changes to the DBDefs.pm file.

I then edited the .env file with the following changes:
MUSICBRAINZ_WEB_SERVER_HOST=musicbrainz.myurl.com
MUSICBRAINZ_WEB_SERVER_PORT=80

Now, I can access everything perfectly at http://172.16.0.10 or https://musicbrainz.myurl.com

Thank You!
