### ISSUE TITLE
New MusicBrainz artists appearing in direct searches but not indexed searches 

### ISSUE THREAD

**Issue by FreqSho** [metabrainz/musicbrainz-docker#186]
Hello. We are having an issue with our MusicBrainz docker mechanism and I’m hoping you can help. The issue is that NEW artist data appearing in MusicBrainz is NOT updating/appearing in our indexed searches of our instance. Our current set-up includes a MusicBrainz mirror server instance with auto-update replication crons configured, and we’re building/rebuilding the search indexes with these commands:

sudo docker-compose run --rm musicbrainz fetch-dump.sh search
sudo docker-compose run --rm search load-search-indexes.sh

We recently optimized the system to best perform with recent MusicBrainz updates and everything seems to be in order. However, new artists that have been added to MusicBrainz are appearing in direct searches but still not appearing in our indexed searches after rebuilding search indexes with previous commands. Do we need to perform some additional steps? Please advise.

**Comment by yvanzo** [comment]
Fixed, see SEARCH-648 for follow-up.
