### ISSUE TITLE
search reindex consistently dies after postgres crashes & reboots during execution 

### ISSUE THREAD

**Issue by marstall** [metabrainz/musicbrainz-docker#188]
Hi, I'm installing musicbrainz the docker way for the first time, coming from using the VM solution. Working through the process, I am running into the following issue. On running

```
sudo docker-compose exec indexer python -m sir reindex
```

It seems to start OK and outputs

```
2021-04-02 16:04:13,557: Importing annotation...
``` 

.... which stays there for awhile as various  normal-looking `search_1` messages go scrolling past in the docker-compose logs. After several minutes, I get the following error:

```
OperationalError: (psycopg2.OperationalError) server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
```

Looking at the docker-compose logs, at the same moment I see:

```
db_1           | 2021-04-02 16:10:58.555 UTC [1] LOG:  server process (PID 609) was terminated by signal 9: Killed
```

This seems to hose the whole script - because while Postgres valiantly restarts itself after this incident, the script quits after emitting a stream of "connection failed" related issues.

I hope I've included enough information here. I am running MacOS Big Sur. Thank you for working on such an amazing project!

**Comment by yvanzo** [comment]
It is recommended to modify your memory settings, see: https://github.com/metabrainz/musicbrainz-docker#modify-memory-settings

**Comment by marstall** [comment]
ah, yes. thank you. i have transitioned to using the straight db dumps because my indexing needs are very speciic - but i'm guessing this would have done the trick. thank you.
