### ISSUE TITLE
Create DB FAILS for newest install version

### ISSUE THREAD

**Issue by PeterCodar** [metabrainz/musicbrainz-docker#194]
The step 
`sudo docker-compose run --rm musicbrainz createdb.sh -fetch`
fails with the error:
```
 ftp://ftp//ftp.eu.metabrainz.org/pub/musicbrainz/data/fullexport/LATEST
           => ‘/media/dbdump/LATEST’
Resolving ftp (ftp)... failed: Temporary failure in name resolution.
wget: unable to resolve host address ‘ftp’
```

I assume, there is a FTP too much. 
Where can we fix that?

**Comment by yvanzo** [comment]
That is a regression.

Immediate workaround:
```bash
sudo docker-compose run --rm musicbrainz fetch-dump.sh replica
sudo docker-compose run --rm musicbrainz createdb.sh
```

**Comment by yvanzo** [comment]
Fixed in `master` branch with commit <https://github.com/metabrainz/musicbrainz-docker/commit/bfeb5addf7030409a8307cb3c34831bcf716587b>. Thanks for the report.
