### ISSUE TITLE
Update Indexes using the Live Data Feed (Remote Search)

### ISSUE THREAD

**Issue by JoshDi** [metabrainz/musicbrainz-docker#216]
Can you please provide instructions on how to use the Update Indexes using the Live Data Feed instructions here for my production slave? 

https://wiki.musicbrainz.org/History:Development/Search_server_setup

**Comment by yvanzo** [comment]
For the record, the above linked age is obsolete.

The current `musicbrainz-docker` documentation covers [setting up search indexes](https://github.com/metabrainz/musicbrainz-docker#set-up-search-indexes) and [keeping search indexes up-to-date](https://github.com/metabrainz/musicbrainz-docker#enable-replication).
