### ISSUE TITLE
Don't re-fetch files that are already up-to-date

### ISSUE THREAD

**Issue by Tails** [metabrainz/musicbrainz-docker#217]
I just ran ```docker-compose run --rm musicbrainz createdb.sh -fetch``` for the first time, but the process terminated during import because the server stopped responding. When I ran this command again, to my surprise I had to resit waiting for all the files to download even though that had just been done. 

Can the data not be downloaded with something like ```rsync``` to prevent redownloading files that are already up-to-date?

**Comment by Tails** [comment]
For future reference, the following worked for me to start over the creation step:

```bash
cd ./musicbrainz-docker && \
	docker-compose stop db && \
	docker volume rm musicbrainz-docker_pgdata && \
       docker-compose run --rm musicbrainz createdb.sh
```

**Comment by yvanzo** [comment]
Thanks for reporting, this is a known issue. See the ticket MBVM-64 details and for follow-up.

**Comment by sankalpjena17** [comment]
You can use rsync to avoid redownloading files that are already up-to-date.

1.Download the MusicBrainz data:- 

rsync -avz --delete-after --partial --progress \
rsync://ftp.musicbrainz.org/pub/musicbrainz/data/fullexport/LATEST/ /path/to/your/local/folder/


2.Run the script:-

docker-compose run --rm musicbrainz createdb.sh -fetch

**Comment by yvanzo** [comment]
For step 2, you can add a Wget option to _finish up a download started by a previous instance of Wget_, as follows:
```sh
docker-compose run --rm musicbrainz createdb.sh -fetch -wget-opts --continue
```

**Comment by yvanzo** [comment]
Closing as this issue MBVM-64 has been resolved last month.

Notes:
1. The scripts are now using `http` instead of `ftp` by default; See releases.
2. The current `rsync` mirror is provided to synchronize further secondary mirrors only, please do not use it directly.
