### ISSUE TITLE
Q: Skip importing/replicating specific tables?

### ISSUE THREAD

**Issue by dgzefem** [metabrainz/musicbrainz-docker#223]
I'm using the MusicBrainz Database to feed some of the data to my own database. However, since I only use a few tables, it's  wasteful and costly for me to have the whole dataset in place.

What I want is essentially:

- to have the Postgres database of MusicBrainz
- to schedule the replication script with the cron
- to only keep the following tables:
  1. `release_group`
  2. `release`
  3. `release_country`
  4. `release_unknown_country`
  5. `cover_art_archive.index_listing`
  6. `cover_art_archive.release_group_cover_art`
  7. `cover_art_archive.image_type`
  8. `artist_credit`
  9. `l_release_group_url`
  10. `url`
  11. `link`
  12. `link_type`
- to not use any other containers from the compose file (indexer, search, mq, musicbrainz)
  - Q: I know the replication script runs in the `musicbrainz` container. Can it be executed from a more lightweight container itself? What's are its dependencies?

This will save me a lot of disk space and RAM, I believe.

Thanks in advance.

**Comment by yvanzo** [comment]
Hi @dgzefem,

I just drafted the pull request https://github.com/metabrainz/musicbrainz-docker/pull/226 to support database-only mirrors. It has to be tested though. It makes the `musicbrainz`container (which runs the replication script) slightly “more lightweight” and doesn’t create unneeded containers. See the ticket MBVM-84 for follow-up.

Partial replication is not really supported as replication packets will insert new entries in empty tables. But you can create your own cron job to regularly clears the tables that you don’t want to keep. There is no plan to make MusicBrainz Server directly supports partial replication but contributions are welcome.

**Comment by dgzefem** [comment]
Hi @yvanzo,

Thanks for the heads up. I'll try this PR (hopefully this week) and get back to you.
