### ISSUE TITLE
In the README.md file, slave.log should now be mirror.log

### ISSUE THREAD

**Issue by JoshDi** [metabrainz/musicbrainz-docker#227]
In v-2022-05-17-mbdb27, slave.log becomes mirror.log so the README.md should reflect that. I tried to push a commit with this change but I was denied unfortunately.

**Comment by yvanzo** [comment]
Thanks for reporting. I made a full report at MBVM-85, and opened a PR for these changes.

Here is an introduction about how to submit changes: https://github.com/metabrainz/guidelines/blob/master/GitHub.md
