### ISSUE TITLE
Schema sequence mismatch - codebase is 27, database is 26

### ISSUE THREAD

**Issue by dgzefem** [metabrainz/musicbrainz-docker#228]
After pulling 3af17009b11eae7f6244310aead210b20fa7b7f5, doing a `docker-compose up --build` and executing the replication script, I get the following in `mirror.log`:

```
Thu May 19 10:59:09 2022 : Schema sequence mismatch - codebase is 27, database is 26
```

Are there any steps required to upgrade my mirrored database?

**Comment by PeterCodar** [comment]
Do you already have executed this steps?

https://blog.metabrainz.org/2022/05/16/musicbrainz-schema-change-release-2022-05-16-with-upgrade-instructions/

**Comment by yvanzo** [comment]
More specifically, instructions for `musicbrainz-docker` are provided in release notes: https://github.com/metabrainz/musicbrainz-docker/releases/tag/v-2022-05-17-mbdb27

More generally, avoid blindly pulling `master` and follow releases instead as these come with instructions and sometimes breaking changes: https://github.com/metabrainz/musicbrainz-docker/releases/
