### ISSUE TITLE
eval $( perl -Mlocal::lib ) may have no effect

### ISSUE THREAD

**Issue by BenOckmore** [metabrainz/musicbrainz-docker#23]
Please correct me if I'm wrong about any of the following - this is just based on my understanding of how Docker works, which may be incorrect!

I haven't yet tested this, but line 24, where `eval $( perl -Mlocal::lib )` is appended to the `~/.bashrc` file, may have no effect on subsequent RUN commands. And the `. ~/.bashrc` part of that command will only affect the current RUN command, and since nothing else is executing following that, it seems to be redundant.

https://github.com/jsturgis/musicbrainz-docker/blob/master/musicbrainz-dockerfile/Dockerfile#L24

RUN uses `/bin/sh`, which may not be set to use bash as the default shell.

I believe that this command is actually unnecessary - if its purpose is to prevent the Perl modules installed for MB polluting the global Perl installation by directing the libraries to be installed in a separate folder (as it seems to be), that doesn't seem to be too important in a Docker image.

Again, if I'm wrong about any of this, please let me know so that I can improve my Docker knowledge!

**Comment by jsturgis** [comment]
Fixed by #26
