### ISSUE TITLE
OSX - InitDb.pl failed due to violation of foreign key constraint `genre_alias_fk_type` 

### ISSUE THREAD

**Issue by JordWyatt** [metabrainz/musicbrainz-docker#231]
MusicBrainz Docker: v-2022-06-20
Docker Compose: 1.29.2
Docker Client/Server: 20.10.11/20.10.11

---

Hi, 

When trying to install the test setup using the instructions described [here](https://github.com/metabrainz/musicbrainz-docker#test-setup) I am running into the following errors:

```
...
Tue Jul 19 22:06:52 2022 : psql:/musicbrainz-server/admin/sql/CreateFKConstraints.sql:1044: ERROR:  insert or update on table "genre_alias" violates foreign key constraint "genre_alias_fk_type"
Tue Jul 19 22:06:52 2022 : DETAIL:  Key (type)=(1) is not present in table "genre_alias_type".
Error during CreateFKConstraints.sql at /musicbrainz-server/admin/InitDb.pl line 93.
Tue Jul 19 22:06:52 2022 : InitDb.pl failed
```

I have tried:
- Recreating the images
- Running `docker-compose run --rm musicbrainz recreatedb.sh`
- Increasing memory allocated to docker container 

Any help would be appreciated, thanks!

**Comment by reosarevok** [comment]
This is an issue where I broke the sample data because I did a dumb, and not connected to your setup specifically. Thanks for letting us know! I'll fix it, and the next sample will work fine, I'll try to get one generated soonish. https://tickets.metabrainz.org/browse/MBS-12512

**Comment by reosarevok** [comment]
I generated a new sample dump which should work, please let me know if it doesn't! :)

**Comment by JordWyatt** [comment]
Working! Thanks very much for your help.
