### ISSUE TITLE
MusicBrainz mirror not working after v-2022-08-08 update

### ISSUE THREAD

**Issue by myopenflixr** [metabrainz/musicbrainz-docker#232]
Hello,

I just completed the update to v-2022-08-08 and MusicBrainz seems to no longer be working. I am receiving an HTTP 500 error when trying to access my mirror.

I saw some unusual errors due the upgrade process,

I'm attaching a "log" file of the output from the upgrade.
[musicbrainz-upgrade.log](https://github.com/metabrainz/musicbrainz-docker/files/9285104/musicbrainz-upgrade.log)

**Comment by mwiencek** [comment]
It seems that Node.js's experimental ES module loader API changed sometime within version 16.  The Dockerfile here installs Node v16.1.0, and I believe this can be fixed by bumping the version to 16.16.0 and rebuilding the image.  We'll have to find a workaround for older 16.x versions too.

**Comment by myopenflixr** [comment]
Is there anything I can do on my end, or should I wait for a fix on your end?

Luckily, I was able to restore a snapshot from 1am this morning to get back up and running until issue(s) resolved.

**Comment by mwiencek** [comment]
Since you were able to restore a snapshot, probably just wait for a fix on our end. :)

I opened https://github.com/metabrainz/musicbrainz-server/pull/2597 which should resolve this, though @yvanzo might also consider upgrading the version of Node.js here to v16.16.0 -- that would also resolve the issue and avoid having to wait for another musicbrainz-server release.

**Comment by JoshDi** [comment]
@yvanzo changing the node.js version in build/musicbrainz/Dockerfile to 16.16.0 fixes the problem

**Comment by yvanzo** [comment]
@mwiencek, @JoshDi: I updated Node.js to v16.16.0 in commit https://github.com/metabrainz/musicbrainz-docker/commit/1b59c6ac8b67a780d250426acf76ef82e756ac10 after succesfully testing it with a mirror server.

@myopenflixr: Update instructions are now available for the latest release [`v-2022-08-09`](https://github.com/metabrainz/musicbrainz-docker/releases/tag/v-2022-08-09). Sorry for the inconvenience and thank you for having reported this issue.

**Comment by myopenflixr** [comment]
Update was successful this time around.

Thank you everyone for the quick fix!
