### ISSUE TITLE
Postgres Dockerfile doesn't follow best practices

### ISSUE THREAD

**Issue by BenOckmore** [metabrainz/musicbrainz-docker#24]
Couple of issues here, based on https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices
1. https://github.com/jsturgis/musicbrainz-docker/blob/master/postgres-dockerfile/Dockerfile#L5 and https://github.com/jsturgis/musicbrainz-docker/blob/master/postgres-dockerfile/Dockerfile#L7 should be merged so that the layer created by line 5 isn't incorrectly cached.
2. I'd split the "RUN cd ... & ..." into seperate WORKDIR and RUN commands, as advised in https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#workdir - mainly for readability. This isn't a huge thing so not that important if you feel otherwise.

I've updated my own fork to resolve these things, so I could make a PR for this if you like.

**Comment by ghost** [comment]
Hi thanks for the great feedback, if you could submit a PR that would be great.
