### ISSUE TITLE
Using sudo to run Docker commands in docs

### ISSUE THREAD

**Issue by bitplane** [metabrainz/musicbrainz-docker#241]
There's no need to do this as long as your user is in the right group (log out and in again after being added)

**Comment by yvanzo** [comment]
Thank you, that’s correct but it isn’t required to have your user in such group either, and `sudo` is more often installed.

Multiple ways of running Docker are supported in both docs and scripts; See [`admin/lib/common.inc.bash`](https://github.com/metabrainz/musicbrainz-docker/blob/v-2022-09-06/admin/lib/common.inc.bash). It is less efforts for users to optionally skip `sudo` when reading the docs than to mandatorily have to add it if it was missing from the docs.

**Comment by bitplane** [comment]
Fair enough. I was messing with the data and it just seemed odd and kinda reckless to elevate commands to root without good reason. Kinda like using a chainsaw to open a door; it works but you should probably try your key first.

**Comment by yvanzo** [comment]
Both allow privilege escalation; See <https://www.hackingarticles.in/docker-privilege-escalation/>. `sudoers` can be restricted to selected commands and parameters, not `docker` group.
