### ISSUE TITLE
Download of new search index loads replication data

### ISSUE THREAD

**Issue by Hobbabobba** [metabrainz/musicbrainz-docker#247]
Suddenly downloading a new search index behaves strange:
```
./admin/delete-search-indexes all
sudo docker-compose run --rm musicbrainz fetch-dump.sh search
```
starts the download from `http://ftp.eu.metabrainz.org/pub/musicbrainz/data/search-indexes/`
after the download from `http://ftp.eu.metabrainz.org/pub/musicbrainz/data/search-indexes/` finished, it started to download all the files from `http://ftp.eu.metabrainz.org/pub/musicbrainz/data/replication/`

Is this behaviour normal? I never saw it happen before.
If i delete all the files from `http://ftp.eu.metabrainz.org/pub/musicbrainz/data/replication/` on my local disk and continue with
```
sudo docker-compose run --rm search load-search-indexes.sh --force
```
everything works fine.

`git status` shows
```
HEAD detached at v-2023-04-17
nothing to commit, working tree clean
```

**Comment by yvanzo** [comment]
There was a regression in that release, please upgrade to the latest release.
See https://github.com/metabrainz/musicbrainz-docker/releases
