### ISSUE TITLE
Schema upgrade 27 to 28 dockerfile references wrong tag?

### ISSUE THREAD

**Issue by Hitobat** [metabrainz/musicbrainz-docker#248]
For the latest schema upgrade, I tried building a new docker container and running upgrade.sh script.
However it says it is expecting the DB to be schema 26, and my DB is already schema 27.

I think I eventually found the problem; the musicbrainz Dockerfile is still one version behind.
https://github.com/metabrainz/musicbrainz-docker/blob/master/build/musicbrainz/Dockerfile#L53
```
ARG MUSICBRAINZ_SERVER_VERSION=v-2023-05-02
```
I believe this should now read `v-2023-05-15-schema-change` instead.

**Comment by yvanzo** [comment]
Sorry about that. I tested the upgrade steps before the git tag were set. Fixed it now.

Just published the upgrade instructions: See https://github.com/metabrainz/musicbrainz-docker/releases/tag/v-2023-05-16-mbdb28

**Comment by yvanzo** [comment]
Actual release is https://github.com/metabrainz/musicbrainz-docker/releases/tag/v-2023-05-16-mbdb28
