### ISSUE TITLE
musicbrainz-docker-db container shuts down when trying initdb

### ISSUE THREAD

**Issue by seth814** [metabrainz/musicbrainz-docker#260]
I am using musicbrainz from git commit: Upgrade MusicBrainz Server to v2023-10-02

I was able to build all images using
`docker-compose build`
then
`docker-compose up -d`

The db container continually tries to restart.
`docker logs musicbrainz-docker-db-1`
![Screenshot from 2023-10-05 14-44-33](https://github.com/metabrainz/musicbrainz-docker/assets/17873279/f83f5abf-921d-405c-aba9-5398d52e54e5)
I don't think it has anything to do with env vars. I tried setting the ones from the error message in .env. Same thing.
The server ownership thing would make sense, but I also stalled the container and exec'd into it to check: `/var/lib/postgresql`
The directory was owned by `postgres:postgres`
Which is what I would expect.
I have another server I setup several months ago, and these configs are the same as far as I can tell.
That one is still up and running though. Never had this issue before.

**Comment by yvanzo** [comment]
Thanks for reporting. It is a known recent issue (apparently from ~2 days ago)  with the newly rebuilt upstream `postgres:12` image. It will be addressed soon with the pull request https://github.com/metabrainz/musicbrainz-docker/pull/259.

**Comment by seth814** [comment]
Thank you! It seems to be working now. Those env vars...
