### ISSUE TITLE
"docker-compose build" seems broken

### ISSUE THREAD

**Issue by kstillson** [metabrainz/musicbrainz-docker#275]
trying to build a local docker instance as-per instructions at https://github.com/metabrainz/musicbrainz-docker.  System is Ubuntu 22.04.04 LTS, docker 24.0.5.  (also tried with rootless podman-compose v4.6.2, but got the same results).  I'm working with a fresh git clone as of 2024-04-12, it's commit 513b15544.. and tagged "v-2024-04-10-hotfix".

Initial "docker-compose build" results in the build error from issue #[263](https://github.com/metabrainz/musicbrainz-docker/issues/263), and edwhardo's [patch](https://github.com/metabrainz/musicbrainz-docker/issues/263#issuecomment-1880418317) fixes that and allows to continue.

2nd attempt at "docker-compose build" is where I'm stuck.  It results in:
```
! Installing the dependencies failed: Installed version (1.41) of DateTime::Locale is not in range '== 1.40'
! Bailing out the installation for ..
366 distributions installed
The command '/bin/bash -o pipefail -c eval "$(perl -Mlocal::lib)" &&     cpanm --installdeps --notest . &&     cpanm --notest         Catalyst::Plugin::StackTrace         Plack::Handler::Starlet         Plack::Middleware::Debug::Base         Server::Starter         Starlet         Starlet::Server         Term::Size::Any         &&     rm -rf /root/.cpan* /root/perl5/man/' returned a non-zero code: 1
ERROR: Service 'musicbrainz' failed to build : Build failed
```

I suspect there's some combination of perl deps that weren't version tagged and which have evolved to have incompatible version requirements for DateTime:Locale.  

Looking further back in the build log, it appears that both versions 1.40 and 1.41 of Locale were installed, I guess some dep check is objecting that 1.41 has become the default (and apparently "--notest" doesn't disable whatever this test is).

Unfortunately, it appears that the docker-compose build environment is ephemeral, and basically ceases to exist as soon as the build fails, so it's really hard to go in and debug further (e.g. to figure out which deps have the conflict).

Alas, I've got no idea how to continue, but would be happy to provide further details

**Comment by yvanzo** [comment]
Hi, edwhardo’s patch is due to their system not keeping file ownerships/permissions as in the git repository. You shouldn’t need it otherwise. Are you in a similar situation?

```sh
# print some info on file permissions and the underlying filesystem
ls -l build/musicbrainz/scripts/
mount | grep $(findmnt -n -o SOURCE --target .)
```

For your 2nd attempt, I suspect that some cache from your 1st attempt may have interfered, as I successfully built the image just now as follows:

```sh
sudo docker-compose build --progress=plain --no-cache musicbrainz
```

**Comment by kstillson** [comment]
many thanks for moving me forward!

so- appears that the problem with my first pass is almost certainly that I've got container user-id namespacing turned on.  There must be some assumption in the build scripts that uid's on the host match those inside the container, which isn't true for me (and does sometimes cause permissions problems).  However, as mentioned, the patch for #263 did get me past that.

But the suggestion of running the build again with the cache turned off didn't work.  Actually I initially got an error that the "--progress" flag wasn't recognized, so presumably I'm using a different version of docker than expected.  Anyway, removed that flag, and after an hour of futzing with it, still couldn't get the build to work.  (Too many variations to try to list here.)

What I ended up doing was setting up a new virtual machine with a completely clean install of Ubuntu 23.10 server and using that (with no uid namespacing) for the build.  That (eventually) worked.  Then I used "docker save" to export the images, and "podman load" to load them into rootless podman.  

I had to modify the docker-compose.yaml file to tell it to use the locally built image, but that's easy.  Now I'm a few steps down and downloading the database, so hopefully I'm on my way.

This seems like a rather complex and slightly delicate build process- I take it there used to be pre-built images but they were discontinued..  I suppose there were good reasons for that, but having pre-built ones certainly would have made my process easier..

Anyway thanks again- I'll go ahead and close this.  Apologies for the distraction, and thanks again for the pointer in the right direction.

**Comment by yvanzo** [comment]
Thanks for your feedback!

> so- appears that the problem with my first pass is almost certainly that I've got container user-id namespacing turned on. There must be some assumption in the build scripts that uid's on the host match those inside the container, which isn't true for me […] and "podman load" to load them into rootless podman.

We are not using Podman indeed, Docker is required. I guess that these don’t have the same behavior or don’t come with the same default settings. Glad to hear that you achieved to make it run using Podman still. I hope that the upcoming prebuilt images will make it much easier to use for you.

> I take it there used to be pre-built images but they were discontinued.. I suppose there were good reasons for that, but having pre-built ones certainly would have made my process easier..

There used to be prebuilt VirtualBox VMs running the Docker Compose project, not prebuilt Docker images. We gave it up for several reasons: too slow compared to running Docker directly on a Linux system, too much maintenance overhead…

However I’m currently working on prebuilt Docker images for the service `musicbrainz` for the next release mid-May.

**Comment by kstillson** [comment]
I got all my media re-tagged and am very pleased-- musicbrainz is ultra-cool;  and once I got used to the Picard interface- absolutely love it too. 

Prebuilt Docker images would make it easier to get going, so I'm very happy to hear that's coming soon.  Thanks again for all your good work- and for even taking the time to help folks like me make their way forward..   😎😎
