### ISSUE TITLE
Indexing Counts No Longer Match, Cannot Delete Index counts

### ISSUE THREAD

**Issue by JoshDi** [metabrainz/musicbrainz-docker#283]
MusicBrainz Docker: v-2024-06-24-dirty
Docker Compose: 2.27.0
Docker Client/Server: 27.0.3/27.0.3

This issue seems to have started at v-2024-06-24. My DB vs Index table counts no longer match:

```
CORE           STATUS  INDEX     DB
editor         OK      0         /0
instrument     OK      1048      /1048
series         --      24143     /24142
place          --      65206     /65199
event          --      82487     /82485
area           OK      119221    /119221
tag            --      215565    /215558
cdstub         --      277607    /277580
label          --      278385    /278365
annotation     --      702067    /697423
work           --      2134916   /2134862
artist         --      2394821   /2394670
release-group  --      3297877   /3297582
release        --      4232260   /4232123
url            --      12373315  /12372905
recording      --      32491369  /32534243

```

I have manually reindexed each table via this command: 
`docker-compose exec -T indexer python -m sir reindex --entity-type series`

But the index count doesnt change. I also tried just deleting the index (via `admin/delete-search-indexes series`), but I still get the same index count (i.e. it doesnt go to 0 as expected)

Any ideas how to resolve? Thank you!

**Comment by yvanzo** [comment]
Deleting the index is asynchronous, there is a short delay before the count goes down to 0.

**Comment by JoshDi** [comment]
hi @yvanzo - yes, I am aware there is a short delay before the count goes to zero. Unfortunately, I am not seeing the index counts changing at all in a few days. The scripts run successfully without any errors (to reindex or delete an index), but it doesnt look like the index counts end up changing. 

I may have to delete my DB and start off clean - unless you have an alternative suggestion.

**Comment by yvanzo** [comment]
Another way to clean up the search indexes entirely:
```bash
docker-compose stop search
docker-compose rm search
# Assuming the project name is `musicbrainz-docker`
docker volume rm `musicbrainz-docker_solrdata`
docker-compose up -d search
```

**Comment by JoshDi** [comment]
hi @yvanzo - so I tried these steps first [https://github.com/metabrainz/musicbrainz-docker?tab=readme-ov-file#recreate-database-with-indexed-search](https://github.com/metabrainz/musicbrainz-docker?tab=readme-ov-file#recreate-database-with-indexed-search)

which didnt work - index counts still matched. 

However, when I ran the commands above that you shared, it fixed the problem and indexing worked again. Thanks
