### ISSUE TITLE
Unable to connect to MBS

### ISSUE THREAD

**Issue by derat** [metabrainz/musicbrainz-docker#284]
I've been having trouble connecting to the MBS in my local dev checkout. I can see `docker-proxy` listening on port 5000, but connections to it are immediately closed; I assume that the proxy isn't able to talk to the server.

My musicbrainz-server checkout is at [a0e143c1](https://github.com/metabrainz/musicbrainz-server/commit/a0e143c1aa965f35d27a5722f0ccd451128b4096) and my musicbrainz-docker checkout is at 5a31b7c47b148c7e3db8ac3b6778b2c2aa14b548. I tried to blow everything away by following the steps in the "Cleanup" and "Removal" sections of `README.md` and then following "Local development of MusicBrainz Server". 

Here's my version info (running in a Debian 12.6 container on a Chromebook):

```
MusicBrainz Docker: v-2024-06-24
Docker Compose: 1.29.2
Docker Client/Server: 20.10.24+dfsg1/20.10.24+dfsg1
```

Here's my `.env` file:

```
MUSICBRAINZ_WEB_SERVER_HOST=<system's IP on my LAN>
MUSICBRAINZ_WEB_SERVER_PORT=5000
MUSICBRAINZ_DOCKER_HOST_IPADDRCOL=0.0.0.0:
MUSICBRAINZ_SERVER_LOCAL_ROOT=/path/to/musicbrainz-server
#MUSICBRAINZ_SEARCH_SERVER=127.0.0.1:8983
COMPOSE_FILE=docker-compose.yml:local/compose/musicbrainz-stopped.yml:compose/musicbrainz-dev.yml
```

I was hoping that I'd be able to see what the problem is in the output from `sudo docker-compose up`, but I don't see any messages from the `musicbrainz` container, just normal-seeming messages from `db_1`, `redis_1`, `search_1`, `validator_1`, `indexer_1`, and `mq_1`.

`docker-compose ps` seems to suggest that everything is up:

```
              Name                            Command               State                               Ports                            
-----------------------------------------------------------------------------------------------------------------------------------------
musicbrainz-docker_db_1            docker-entrypoint.sh postg ...   Up      5432/tcp                                                     
musicbrainz-docker_indexer_1       /sbin/my_init                    Up                                                                   
musicbrainz-docker_mq_1            /docker-entrypoint-wrapper.sh    Up      15671/tcp, 15672/tcp, 25672/tcp, 4369/tcp, 5671/tcp, 5672/tcp
musicbrainz-docker_musicbrainz_1   docker-entrypoint.sh /bin/ ...   Up      0.0.0.0:5000->5000/tcp                                       
musicbrainz-docker_redis_1         docker-entrypoint.sh redis ...   Up      6379/tcp                                                     
musicbrainz-docker_search_1        docker-entrypoint.sh solr- ...   Up      8983/tcp                                                     
musicbrainz-docker_validator_1     ./vnu-runtime-image/bin/ja ...   Up      8888/tcp
```

I'm not able to see any logs from the `musicbrainz` service, though:

```
% docker-compose logs musicbrainz
Attaching to musicbrainz-docker_musicbrainz_1
%
```

Can you suggest anything else to try to debug this?

**Comment by yvanzo** [comment]
In your file `.env`, the Docker Compose environment variable `COMPOSE_FILE` contains `local/compose/musicbrainz-stopped.yml`. You should also be able to see it from the output of the command `admin/configure show`. Not sure where it comes from. Just remove it from your configuration as follows:

```bash
admin/configure rm local/compose/musicbrainz-stopped.yml
docker-compose up -d musicbrainz
```

**Comment by derat** [comment]
Thanks, that fixed it!

IIRC my VM hung once back when I was trying to apply a schema update -- I suspect that that's what left the service in a stopped state.
