### ISSUE TITLE
Windows 10 Docker issue

### ISSUE THREAD

**Issue by ghost** [metabrainz/musicbrainz-docker#33]
When I run docker-compose up -d

I get this:
musicbrainzdocker_postgresql_1 is up-to-date
musicbrainzdocker_search_1 is up-to-date
musicbrainzdocker_postgresqldata_1 is up-to-date
Starting musicbrainzdocker_indexer_1
Starting musicbrainzdocker_musicbrainz_1

ERROR: for musicbrainz  Cannot start service musicbrainz: oci runtime error: exec: "/start.sh": permission denied
[31mERROR[0m: Encountered errors while bringing up the project.

I'm in Windows 10 pro, docker 1.12.1 build 23cf638

**Comment by jsturgis** [comment]
Hi did this turn out to not be an issue?
