### ISSUE TITLE
Null pointer exception when building search indexes

### ISSUE THREAD

**Issue by nicolas-pickelny** [metabrainz/musicbrainz-docker#36]
Im getting this error when trying to build the database indexes

[ec2-user@ip-172-30-2-201 musicbrainz-docker]$ docker-compose run --rm indexer /home/search/index.sh
Index Builder Started:18:28:22
recording: Unable to get replication information
tmp_artistcredit:Started at:18:28:23
tmp_artistcredit:Finished:0.0 secs
tmp_artistcredit:Created Indexes:0.0 secs
tmp_release     :Started at:18:28:23
tmp_release     :Finished:0.0 secs
tmp_release     :Created Indexes:0.0 secs
tmp_release_event     :Started at:18:28:23
tmp_release_event     :Finished:0.0 secs
tmp_release_event     :Created Indexes:0.0 secs
tmp_track       :Started at:18:28:23
tmp_track       :Finished:0.0 secs
tmp_track       :Created Indexes0.0 secs
recording:Started at 18:28:23
Exception in thread "main" java.lang.NullPointerException
	at org.musicbrainz.search.index.DatabaseIndex.addMetaInformation(DatabaseIndex.java:151)
	at org.musicbrainz.search.index.IndexBuilder.buildDatabaseIndex(IndexBuilder.java:265)
	at org.musicbrainz.search.index.IndexBuilder.main(IndexBuilder.java:164)
[ec2-user@ip-172-30-2-201 musicbrainz-docker]$ 

I dont know what to do, any answer would be apreciated

Thank you
Nico

**Comment by nelgin** [comment]
It would be nice if the resolution was posted. I got this error and there is no fix posted anywhere.
