### ISSUE TITLE
Error setting up a new EC2 instance

### ISSUE THREAD

**Issue by nicolas-vazquez** [metabrainz/musicbrainz-docker#48]
I am experiencing issues setting up a new instance with the new applied changes. I ran `sudo docker-compose up -d` without errors, but the indexer container exits with code 1. When I attempted to index I got the following error:

`Index Builder Started:20:33:19
recording: Unable to get replication information
tmp_artistcredit:Started at:20:33:19
Exception in thread "main" org.postgresql.util.PSQLException: ERROR: relation "artist_credit_name" does not exist
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:1592)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1327)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:192)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:451)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:336)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:328)
	at org.musicbrainz.search.index.CommonTables.createArtistCreditTableUsingDb(CommonTables.java:65)
	at org.musicbrainz.search.index.CommonTables.createTemporaryTables(CommonTables.java:197)
	at org.musicbrainz.search.index.IndexBuilder.main(IndexBuilder.java:151)`

When I run `sudo docker exec musicbrainzdocker_musicbrainz_1 ./admin/replication/LoadReplicationChanges` I get `Can't locate JSON.pm in @INC (you may need to install the JSON module) (@INC contains: /musicbrainz-server/admin/replication/../../lib /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at /musicbrainz-server/admin/replication/../../lib/DBDefs/Default.pm line 32.
BEGIN failed--compilation aborted at /musicbrainz-server/admin/replication/../../lib/DBDefs/Default.pm line 32.
Compilation failed in require at /usr/share/perl/5.22/parent.pm line 20.
BEGIN failed--compilation aborted at /musicbrainz-server/admin/replication/../../lib/DBDefs.pm line 29.
Compilation failed in require at ./admin/replication/LoadReplicationChanges line 32.
BEGIN failed--compilation aborted at ./admin/replication/LoadReplicationChanges line 32.`

Someone can help me out?

**Comment by jsturgis** [comment]
Hi when did you last do a pull?

**Comment by nicolas-vazquez** [comment]
If you mean of this repo I am up to date. Today I created the instance and got the errors I described above. I made these steps:

1.) Install docker and docker-compose
2.) Clone this repo
3.) `sudo docker-compose up -d`

After that all that I tried gave me errors. I missed something? What should I have done after that last step?

Thanks!

**Comment by jsturgis** [comment]
Ok you will need to pull again and run `sudo docker-compose run --rm musicbrainz /createdb.sh -fetch` I just fixed a bug in the createdb script. I think the indexer is complaining because the db hasn't been populated yet.

If you get an error that the DB already exists run `sudo docker-compose run --rm musicbrainz /recreatedb.sh`

**Comment by jsturgis** [comment]
I am going to close this, reopen if you still have problems.

**Comment by nicolas-vazquez** [comment]
Thank you very much for your response. With the latest changes I was able to make a recreate and a full index but when I ran `sudo docker-compose up -d` `musicbrainzdocker_indexer_1` exit with 1 code and `musicbrainzdocker_postgresqldata_1` exit with 0 code and I'm not able to load the CSS for the slave site. But I was able to perform searches without issues. Do you have any idea on that?

Thanks!
