### ISSUE TITLE
Unable to index DB

### ISSUE THREAD

**Issue by gterts** [metabrainz/musicbrainz-docker#50]
Here's the output when attempting to index:
```
musicbrainz:~/musicbrainz-docker$ sudo docker-compose run --rm indexer /home/search/index.sh
ERROR: No such service: indexer
```

In the latest docker-compose.yml, the indexer section was removed from the file but the "index.sh" script doesn't appear to be in the search container.

**Comment by gterts** [comment]
Prior to running "sudo docker-compose up -d"
Moved index.sh from /musicbrainz-docker/indexer-dockerfile to /musicbrainz-docker/search-dockerfile
Changed /musicbrainz-docker/search-dockerfile/Dockerfile to:

```
FROM jetty:9.3.10

MAINTAINER Robert Kaye <rob@metabrainz.org>

WORKDIR $JETTY_HOME
RUN curl -o $JETTY_HOME/webapps/ROOT.war http://ftp.musicbrainz.org/pub/musicbrainz/search/servlet/searchserver.war

WORKDIR /home/search
RUN curl -o /home/search/index.jar http://ftp.musicbrainz.org/pub/musicbrainz/search/index/index.jar

COPY index.sh /home/search

VOLUME ["/home/search/data"]
```

Then ran:
sudo docker-compose run --rm search /home/search/index.sh

instead of:
sudo docker-compose run --rm indexer /home/search/index.sh

**Comment by jsturgis** [comment]
Hey thanks for bringing this up, I removed the indexer from the compose file because it doesn't need to run every time musicbrainz is started. I updated the instructions for running the indexer and exposed the db ports, please pull down the latest and let me know if it works now.

**Comment by jsturgis** [comment]
Hey thanks for bringing this up, I added the indexer service back into the compose file.
