### ISSUE TITLE
Issue when running recreatedb script

### ISSUE THREAD

**Issue by nicolas-vazquez** [metabrainz/musicbrainz-docker#51]
Hi,

I'm experiencing issues with the latest changes when running `sudo docker-compose run --rm musicbrainz /recreatedb.sh`

I'm getting this output in every run:

`psql: warning: extra command-line argument "postgres" ignored
psql: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?`

Tried different postgres configuration changes but I had no luck.
Someone there experiencing same issue?

Thanks!

**Comment by nicolas-vazquez** [comment]
After changing `$DB_ENV_POSTGRES_USER` with `$POSTGRES_USER` in the recreatedb script I get this output:

`Error in tempdir() using /media/dbdump/tmp/MBImport-XXXXXXXX: Parent directory (/media/dbdump/tmp) does not exist at /musicbrainz-server/admin/MBImport.pl line 132.
Failed to import dataset.`

Any thought on this?

Thanks!

**Comment by jsturgis** [comment]
Hi, that issue should be fixed now please pull the latest version and try again.
