### ISSUE TITLE
[FR] Possibility to choose source (FTP, http)?

### ISSUE THREAD

**Issue by PeterCodar** [metabrainz/musicbrainz-docker#53]
Actually, the official MusicBrainz FTP servers are slow like hell.
Could you please let the user choose (optionally) the source for the needed "searchserver.war" and the fulldump *.bz2?

I think about something like 
`createdb.sh -fetch "ftp://myown.fast.sourceserver" or "http://evenfaster.webserver"`

**Comment by mayhem** [comment]
I plan to do exactly that -- our EU mirror in paris is considerably faster than the official mirror.

**Comment by jsturgis** [comment]
Switched to the EU mirror.
