### ISSUE TITLE
ERROR:  database "musicbrainz" already exists / createdb.sh

### ISSUE THREAD

**Issue by PeterCodar** [metabrainz/musicbrainz-docker#54]
I follow your instructions, but whatever I do, I can't solve the step "Create Database":

```
ubuntu@ubuntu:~/musicbrainz-docker$ sudo docker-compose run --rm musicbrainz /createdb.sh
found existing dumps
Tue Aug  1 19:37:07 2017 : InitDb.pl starting
Tue Aug  1 19:37:07 2017 : Creating database 'musicbrainz'
Failed query:
	'CREATE DATABASE musicbrainz WITH OWNER = musicbrainz TEMPLATE template0 ENCODING = 'UNICODE' LC_CTYPE='C' LC_COLLATE='C''
	()
42P04 DBD::Pg::st execute failed: ERROR:  database "musicbrainz" already exists [for Statement "CREATE DATABASE musicbrainz WITH OWNER = musicbrainz TEMPLATE template0 ENCODING = 'UNICODE' LC_CTYPE='C' LC_COLLATE='C'"]
 at /musicbrainz-server/admin/../lib/Sql.pm line 115.
	Sql::catch {...} (MusicBrainz::Server::Exceptions::DatabaseError=HASH(0x2d33d40)) called at /usr/share/perl5/Try/Tiny.pm line 115
	Try::Tiny::try(CODE(0x2c49120), Try::Tiny::Catch=REF(0x2b556c8)) called at /musicbrainz-server/admin/../lib/Sql.pm line 116
	Sql::do(Sql=HASH(0x2afdb10), "CREATE DATABASE musicbrainz WITH OWNER = musicbrainz TEMPLATE"...) called at /musicbrainz-server/admin/InitDb.pl line 218
	main::Create("MAINTENANCE") called at /musicbrainz-server/admin/InitDb.pl line 523
Tue Aug  1 19:37:07 2017 : InitDb.pl failed
ubuntu@ubuntu:~/musicbrainz-docker$ 
```

Where should I change which lines to import the existing data dumps?
Why does the database already exist if I have not executed the "createdb.sh" before?

**Comment by mayhem** [comment]
The InitDB.pl call needs to not have the --createdb argument. I hope to have another PR to this effect tomorrow after more testing.

**Comment by jsturgis** [comment]
I merged in the changes from @mayhem please pull the latest version and try again.

**Comment by daviestar** [comment]
Hello, I think this issue has returned - I get the error above when running `createdb.sh`.  

After, running `recreate.db` appears to work.

**Comment by jsturgis** [comment]
@daviestar this error might happen if you have already created the DB, in that case recreate will work because it first removes the DB then runs the create script.

**Comment by daviestar** [comment]
@jsturgis i must have test-deployed this repo 100 times in the past week at work! mainly on fresh ec2 instances. 

https://github.com/jsturgis/musicbrainz-docker/commit/c397f078fc6d70f2589b12be403fd79bff05d62a then later https://github.com/jsturgis/musicbrainz-docker/commit/fbaab0e7da3831ab473ab2067da327e50269fcf7

aside from this work-aroundable issue it's a fantastic one-click script, thanks very much.

**Comment by jsturgis** [comment]
@daviestar thanks I'm glad it's working well for you, I submitted another fix for the issue you mentioned, once I merge it you should not see the problem anymore.
