### ISSUE TITLE
"Nice" CSS will not be loaded

### ISSUE THREAD

**Issue by PeterCodar** [metabrainz/musicbrainz-docker#55]
I followed your instructions step by step.
After creating the search index I rebooted my ubuntu and restarted the container with
`sudo docker-compose up `

I can access the local webserver with 192.168.1.35:5000, but I get a "text-only" output, there is no "nice" CSS or color.

Somewhere I read, that I have to change the line 
`sub WEB_SERVER { "localhost:5000" }`
to
`sub WEB_SERVER { "192.168.1.35:5000" }`

Is this manual step still necessary?

Where exactly do I have to do that? 
Inside the running "musicbrainzdocker_musicbrainz_1" container? 
Inside the file /musicbrainz-server/lib/DBDefs.pm?
Anywhere else?

**Comment by jsturgis** [comment]
Hi, if you access the server at 192.168.1.35 then you will need to make the change you suggested.

```sub WEB_SERVER { "192.168.1.35:5000" }```

Let me know if that does not work.

**Comment by PeterCodar** [comment]
WHERE should I change this line?

**Comment by jsturgis** [comment]
@PeterCodar you should make the change [here](https://github.com/jsturgis/musicbrainz-docker/blob/master/musicbrainz-dockerfile/DBDefs.pm#L158)

**Comment by fergalmoran** [comment]
Make sure to do "docker-compose build" afterwards or changes won't be written to the container.

**Comment by BourneLoser** [comment]
Thanks to this thread, I was able to solve the issue. However for me, simply adding the following line to .env worked:
`MUSICBRAINZ_WEB_SERVER_HOST=myhost`
