### ISSUE TITLE
How to check if replication is up and running?

### ISSUE THREAD

**Issue by PeterCodar** [metabrainz/musicbrainz-docker#57]
README.md:
Could you please add the command to check if the replication is up and running?
Or at least show the last logfile entries about the replication?

**Comment by jsturgis** [comment]
Sure good idea thanks, I also just fixed an issue with the replication cron job that prevented it from running.

**Comment by jsturgis** [comment]
Fixed by 73421fd5a50037cd466b2c81df6cc1198679d467
