### ISSUE TITLE
/recreatedb.sh can't connect..

### ISSUE THREAD

**Issue by skywiseca** [metabrainz/musicbrainz-docker#60]
Following the directions to get musicbrainz setup and got as far as DLing and creating the DB, got a failure.
I was going to try and recreate the DB and try again but...
---
xxx@docker01:~/musicbrainz-docker$ sudo docker-compose run --rm musicbrainz /recreatedb.sh
psql: warning: extra command-line argument "postgres" ignored
psql: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
xxx@docker01:~/musicbrainz-docker$
---
Postgres is running.

**Comment by nicolas-vazquez** [comment]
I was able to make it run changing `$DB_ENV_POSTGRES_USER` with `$POSTGRES_USER`

**Comment by jsturgis** [comment]
Fixed by 94bd4b92e1d20013a599cc309a5d89a5a274ef33 and 193b0c7b227863c32bcfab58180492cef72b7b79.
