### ISSUE TITLE
Error when creating the database with createdb script

### ISSUE THREAD

**Issue by nicolas-vazquez** [metabrainz/musicbrainz-docker#61]
Hi, 

When I attempt to create the database with `sudo docker-compose run --rm musicbrainz /createdb.sh -fetch` I get the following error:

`Error in tempdir() using /media/dbdump/tmp/MBImport-XXXXXXXX: Parent directory (/media/dbdump/tmp) does not exist at /musicbrainz-server/admin/MBImport.pl line 132.`

Someone experiencing the same issue?

Thanks!

**Comment by fergalwasp** [comment]
Yes - same here, pretty sure my local dump volume is mapped correctly.

**Comment by fergalmoran** [comment]
Yes - same here, pretty sure my local dump volume is mapped correctly.

View from inside the musicbrainz container.
![image](https://user-images.githubusercontent.com/13272192/30384064-2e6fb3dc-989b-11e7-8d28-822134b24029.png)

I got it to work by running it a second time without the -fetch arg.
