### ISSUE TITLE
Set up a search server

### ISSUE THREAD

**Issue by jsturgis** [metabrainz/musicbrainz-docker#8]
Set up a search server (https://bitbucket.org/metabrainz/search-server/) and reindexing; the default configuration uses the (ratelimited) search.musicbrainz.org. Note that the search server is hopefully soon to be replaced by a system using Solr.

Instructions:
https://wiki.musicbrainz.org/Development/Search_server_setup

**Comment by isuftin** [comment]
@jsturgis Do you know if there's any availability of a Docker container that works as a AcoustID service for apps like Picard?

**Comment by jsturgis** [comment]
Hey, I don't know of any.

**Comment by jsturgis** [comment]
Resolved by #27
