### ISSUE TITLE
DB Schema Name

### ISSUE THREAD

**Issue by williamekwhite** [metabrainz/musicbrainz-docker#87]
The latest commit breaks some of the scripts due to a database name change. The new one is "musicbrainz_db", yet some of the bash scripts are still using "musicbrainz".

Here is the commit -- https://github.com/metabrainz/musicbrainz-docker/commit/ec772597474deb0fd3e5c1a2eb6058f84f137596

Some scripts that I have had to modify:

`indexer-dockerfile/index.sh`
`musicbrainz-dockerfile/scripts/recreatedb.sh`

**Comment by yvanzo** [comment]
Thanks for reporting that bug and sorry for the inconvenience, I’m the culprit.
