### ISSUE TITLE
Container not running error

### ISSUE THREAD

**Issue by undeadindustries** [metabrainz/musicbrainz-docker#97]
Any ideas on how to fix this? (Running in Win10pro 64)
```
src\musicbrainz-docker>docker-compose -f docker-compose.yml -f docker-compose.public.yml up -d
musicbrainz-docker_redis_1 is up-to-date
musicbrainz-docker_search_1 is up-to-date
musicbrainz-docker_db_1 is up-to-date
musicbrainz-docker_musicbrainz_1 is up-to-date
Starting musicbrainz-docker_indexer_1 ... done                                                                          
C:\Users\rob\src\musicbrainz-docker>docker exec musicbrainzdocker_musicbrainz_1 /set-token.sh MY_TOKEN
**Error: No such container: musicbrainzdocker_musicbrainz_1**
```

**Comment by yvanzo** [comment]
Yes, instructions assumed an older version of docker-compose. Newer versions may generate container with a different name, here `musicbrainz-docker_*` (instead of former `musicbrainzdocker_*`) which should be used with every `docker exec `… command as in:

```bash
docker exec musicbrainz-docker_musicbrainz_1 /set-token.sh MY_TOKEN
```

**Comment by undeadindustries** [comment]
But I copied and pasted what docker told me it launched?

**Comment by yvanzo** [comment]
It becomes unclear to me what you copied from where. Does the above command work for you?

**Comment by teamrehab** [comment]
Sorry, yes, that worked!

**Comment by undeadindustries** [comment]
Sorry, yes that worked!

**Comment by volgin** [comment]
Why is this issue closed if it has not been resolved? It takes a minute to update the instructions :)

**Comment by yvanzo** [comment]
Because older version of docker-compose is still available on many platforms, including MusicBrainz Virtual Machine. The documentation will be updated with next MB VM release.

**Comment by yvanzo** [comment]
Since the issue has been reported again, I finally documented it by commit https://github.com/metabrainz/musicbrainz-docker/commit/2261442974ad44358495996bc76c872a922db1c9.
