### ISSUE TITLE
Problem creating a database: Schema sequence mismatch - codebase is 24, mbdump.tar.bz2 is 25

### ISSUE THREAD

**Issue by volgin** [metabrainz/musicbrainz-docker#99]
Should I wait for an update to the codebase, or is there a way to get a dump with the previous schema?

**Comment by yvanzo** [comment]
Solved with PR #98.

For the record, there is only one sample dump left with schema 24: http://ftp.musicbrainz.org/pub/musicbrainz/data/sample/20190501-000001/
